### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by ssi02014** [remarkablemark/html-react-parser#1000]
Hello, 👏 @remarkablemark 
I'm looking at the code inside "lib" and it looks like you're still using "var" to declare most variables.

Do you have any plans to migrate to "let" or "const"?
If there is a plan, I'd like to work on it, but what do you think?

**Comment by remarkablemark** [comment]
Thanks for opening this issue @ssi02014! I do plan to eventually migrate to TypeScript but that will be a breaking change this for library.

**Comment by ssi02014** [comment]
@remarkablemark 👍
Thanks for the review!
So, am I correct in understanding that you don't need to do the "let/const" migration beforehand?

### to-be
```js
// attributes-to-props.js
var reactProperty = require('react-property');
var utilities = require('./utilities');

// https://reactjs.org/docs/uncontrolled-components.html
// https://developer.mozilla.org/docs/Web/HTML/Attributes
var UNCONTROLLED_COMPONENT_ATTRIBUTES = ['checked', 'value'];
var UNCONTROLLED_COMPONENT_NAMES = ['input', 'select', 'textarea'];

var VALUE_ONLY_INPUTS = {
  reset: true,
  submit: true
};
```

### as-is
```js
// attributes-to-props.js
const reactProperty = require('react-property');
const utilities = require('./utilities');

// https://reactjs.org/docs/uncontrolled-components.html
// https://developer.mozilla.org/docs/Web/HTML/Attributes
const UNCONTROLLED_COMPONENT_ATTRIBUTES = ['checked', 'value'];
const UNCONTROLLED_COMPONENT_NAMES = ['input', 'select', 'textarea'];

const VALUE_ONLY_INPUTS = {
  reset: true,
  submit: true
};

// ...
```

**Comment by remarkablemark** [comment]
@ssi02014 Yes if we're using TypeScript, then we'll be using ES6 syntax.

**Comment by ssi02014** [comment]
@remarkablemark 
Thanks! 👍👍👍

**Comment by kasperaamodt** [comment]
Any updates on the progress here?

**Comment by remarkablemark** [comment]
@kasperaamodt No update at the moment. I've been pretty busy so I haven't had a chance to work on this.

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1124#issuecomment-1784142628

**Comment by ssi02014** [comment]
🎉🎉🎉
