### ISSUE TITLE
How to get the text from my html element with replace

### ISSUE THREAD

**Issue by blirag** [remarkablemark/html-react-parser#1055]
## Question

My html string is coming from a cms, how can I customize tags like h1, h2, h3, bullet points...?
I've tried using replace, but how do I get the text inside my element to render correctly?

Example:
```javascript 
const options: HTMLReactParserOptions = {
    replace: (domNode: DOMNode) => {
      if (domNode.name === 'h3') {
        return <Heading>how to return my data??</Heading>
      }
    }, 
  }
```

## Keywords

custom tag, replace, transform

**Comment by remarkablemark** [comment]
@blirag see https://github.com/remarkablemark/html-react-parser/tree/v4.2.2?tab=readme-ov-file#replace-element-and-children

You will have to pass `children` to `domToReact`:

```js
import { domToReact } from 'html-react-parser';

const options: HTMLReactParserOptions = {
    replace: (domNode: DOMNode) => {
      if (domNode.name === 'h3') {
        return <Heading>{domToReact(domNode.children)}</Heading>
      }
    }, 
  }
```

**Comment by blirag** [comment]
@remarkablemark thank you so much!
