### ISSUE TITLE
 Curly Brace Symbol Doesn't Show 

### ISSUE THREAD

**Issue by saraOrkide** [remarkablemark/html-react-parser#1080]
I want to parse the mml, but when it comes to the mfenced tag, the value of the open attribute changes from "}" to "true".
I used the latest version and set sanitize for it, but it didn't work
example mml: 
`<div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'>  متناظر با هر عبارت، یک مجموعه و متناظر با هر مجموعه، یک عبارت بنویسید و تعداد عضوهای هر مجموعه را تعیین کنید. </span></div><div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'> الف) <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mi>A</mi><mo>=</mo><mfenced   open="{" close="}" separators="|"><mrow><mn>1,8</mn><mo>,</mo><mn>27,64,125</mn></mrow></mfenced></math></span> </span></div><div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'> ب) <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mi>C</mi><mo>=</mo><mfenced   open="{" close="}" separators="|"><mrow><mn>10</mn></mrow></mfenced></math></span> </span></div><div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'> ج) عددهای طبیعی مضرب <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mn>5</mn></math></span> و کوچکتر از <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mn>100</mn></math></span> </span></div><div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'> د) عددهای طبیعی بزرگتر از <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mn>4</mn></math></span> و کوچکتر از <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mn>5</mn></math></span> </span></div><div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'> هـ) عددهای صحیح منفی که بین <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mn>4</mn></math></span> و <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mn>7</mn></math></span> قرار دارد. </span></div><div class='chistaItem' style='text-align:right;/*MARK-BY-CHISTA-PARSER*/direction:rtl;/*MARK-BY-CHISTA-PARSER*/'><span class='chistaText'> و) عددهای اول دو رقمی که مضرب <span class="chistaFormula"><math xmlns="http://www.w3.org/1998/Math/MathML" display="inline-block"><mi>r</mi></math></span> باشد. </span></div>`

Generally, it sets the value of the open attribute to true

**Comment by remarkablemark** [comment]
@saraOrkide can you provide a reproducible example using [CodeSandbox JavaScript](https://codesandbox.io/s/940pov1l4w) or [CodeSandbox TypeScript](https://codesandbox.io/s/html-react-parser-z0kp6)?

**Comment by saraOrkide** [comment]
> @saraOrkide can you provide a reproducible example using [CodeSandbox JavaScript](https://codesandbox.io/s/940pov1l4w) or [CodeSandbox TypeScript](https://codesandbox.io/s/html-react-parser-z0kp6)?

https://codesandbox.io/s/940pov1l4w?file=/src/index.js

**Comment by remarkablemark** [comment]
@saraOrkide I don't see your changes. Can you fork and save a new CodeSandbox?

**Comment by saraOrkide** [comment]
> @saraOrkide I don't see your changes. Can you fork and save a new CodeSandbox?

Oh sorry, forgot to save
see now

**Comment by remarkablemark** [comment]
@saraOrkide can you share the new link that was created after save?

**Comment by saraOrkide** [comment]
> @saraOrkide can you share the new link that was created after save?

https://codesandbox.io/s/laughing-dhawan-sq5p28?file=/src/index.js

**Comment by remarkablemark** [comment]
I reproduced your issue and it's caused by the `open` prop being converted to a boolean value:

![Screen Shot 2023-10-13 at 1 39 44 PM](https://github.com/remarkablemark/html-react-parser/assets/10594555/43af1542-c8a0-4c70-a8a0-7f3a86cfc552)

See https://codesandbox.io/s/html-react-parser-1080-23nhj2

**Comment by saraOrkide** [comment]
Ok, I know, why does it convert it to boolean?
How can I solve the problem?
 with react-property?!!
Can you please tell me with the sample code that I sent

**Comment by remarkablemark** [comment]
@saraOrkide unfortunately there is nothing I can do on my side since this is a React bug. See [reproduced demo](https://codesandbox.io/s/html-react-parser-1080-23nhj2?file=/src/index.js)

My recommendation is to stick with `dangerouslySetInnerHTML`

**Comment by saraOrkide** [comment]
> My recommendation is to stick with `dangerouslySetInnerHTML`

My problem is that I want to replace a tag, so I wanted to use html-react-parser

**Comment by remarkablemark** [comment]
You can use `dangerouslySetInnerHTML` with `html-react-parser`

**Comment by saraOrkide** [comment]
> You can use `dangerouslySetInnerHTML` with `html-react-parser`

Can you tell me how?

**Comment by Oripovd1** [comment]
Hey @saraOrkide! I also have the same issue here. Could you find any solution?
