### ISSUE TITLE
Is it possible to replace a substring?

### ISSUE THREAD

**Issue by AntoninSlejska** [remarkablemark/html-react-parser#111]
I have string like this:

`"<p>I need to replace this and that substrings.</p>"`

I need to parse the string to HTML:

`<p>I need to replace <span id="0" class="this">???</span> and <span id="1" class="that">???</span> substrings.</p>`

Is it possible to do it in this library? I suppose, it is not possible and I have to replace the substrings with the standard JS method and then parse the string to HTML.

Thanks!

**Comment by remarkablemark** [comment]
It's possible but you still need to break the string into parts and replace the matched substring.

I think it's easier to do it with JavaScript:
```js
var string = '<p>I need to replace this and that substrings.</p>';
string = string.replace('this', '<span id="0" class="this">???</span>');
string = string.replace('that', '<spanid="1" class="that">???</span>');
```

**Comment by AntoninSlejska** [comment]
Thanks!
