### ISSUE TITLE
Vercel Edge not Supported

### ISSUE THREAD

**Issue by deevo-sage** [remarkablemark/html-react-parser#1113]
## Expected Behavior

Should be deployable to Vercel Edge

## Actual Behavior

<img width="747" alt="image" src="https://github.com/remarkablemark/html-react-parser/assets/54073655/7dec56a0-5889-439e-9a52-ab53baed9502">
this error pops up if the runtime is set to 'edge'

## Steps to Reproduce

```js
import parse from "html-react-parser";
export const runtime = "edge";

const html = `<div>hello</div>`;

export default function TestPage() {
  const parsedHTML = parse(html || "", {
    trim: true
  });

  return parsedHTML;
}

```

## Reproducible Demo

https://codesandbox.io/p/sandbox/confident-panini-t7ww8l

## Environment

- Version: 4.2.9
- Platform: Nextjs
- Browser: Arc & Chrome
- OS: Mac OS

**Comment by remarkablemark** [comment]
@deevo-sage can you try this? https://github.com/remarkablemark/html-react-parser/issues/736#issuecomment-1612365781

**Comment by deevo-sage** [comment]
Thanks @remarkablemark , it worked :)
