### ISSUE TITLE
Type errors with v5.0.0

### ISSUE THREAD

**Issue by harryzcy** [remarkablemark/html-react-parser#1126]
The following code gives two errors:
```
const options: HTMLReactParserOptions = {
    replace: (domNode: DOMNode) => {
      if (!(domNode instanceof Element)) return
      if (domNode.name === 'a') {
        domNode.attribs.target = '_blank'
        domNode.attribs.rel = 'noopener noreferrer'
        return domNode // error 1
      }
      if (['html', 'head', 'body'].includes(domNode.name)) {
        return <>{domToReact(domNode.children, options)}</> // error 2
      }
  }
}
```

Error 1:
```
Type '(domNode: DOMNode) => Element | JSX.Element | undefined' is not assignable to type '(domNode: DOMNode) => string | boolean | void | Element | null'.
  Type 'Element | JSX.Element | undefined' is not assignable to type 'string | boolean | void | Element | null'.
    Type 'Element' is not assignable to type 'string | boolean | void | Element | null'.
      Type 'Element' is missing the following properties from type 'ReactElement<any, any>': props, keyts(2322)
```

It seems `HTMLReactParserOptions`'s `replace` expects JSX.Element instead of domhandler's Element

Error 2:
```
Argument of type 'ChildNode[]' is not assignable to parameter of type 'DOMNode[]'.
  Type 'ChildNode' is not assignable to type 'DOMNode'.
    Type 'CDATA' is not assignable to type 'DOMNode'.
      Type 'CDATA' is missing the following properties from type 'Element': name, attribs, tagName, attributests(2345)
```

## Expected Behavior

There's no type errors

## Actual Behavior

Build fails.

## Steps to Reproduce

Use the above code

## Environment

- Version: v5.0.0
- Platform: React & Vite
- Browser: Chrome
- OS: macOS

## Keywords

Type error

**Comment by remarkablemark** [comment]
For the 1st error, can return void since the return type should either be a React element or void:

```diff
-        return domNode // error 1
+        return
```

For the 2nd error, can you type assertion:

```diff
-        return <>{domToReact(domNode.children, options)}</> // error 2
+        return <>{domToReact(domNode.children, options) as DOMNode}</>
```

You can import `DOMNode` from:

```ts
import type { DOMNode } from 'html-react-parser';
```

**Comment by harryzcy** [comment]
Thanks, the method works.

**Comment by remarkablemark** [comment]
I decided to add back the `object` return type for `replace` option in order to fix error 1. See #1129

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1128#issuecomment-1784210866

**Comment by Bkumar48** [comment]
` const options: HTMLReactParserOptions = {
    replace: (domNode: DOMNode) => {
      if (!(domNode instanceof Element)) return;
      if (domNode.name === "ul") {
        return (
          <ul className="grid grid-cols-2">
            {domToReact(domNode.children as DOMNode[])}
          </ul>
        );
      }

      if (domNode.name === "li") {
        return (
          <li className="flex gap-2 items-center ">
            <Icons.PinkArrowMarker />
            {domToReact(domNode.children as DOMNode[])}
          </li>
        );
      }
    },
  };`
  Only first if condition is working, can anyone help me with this?

**Comment by Bkumar48** [comment]
` const options: HTMLReactParserOptions = {
    replace: (domNode: DOMNode) => {
      if (!(domNode instanceof Element)) return;
      if (domNode.name === "ul") {
        return (
          <ul className="grid grid-cols-2">
            {domToReact(domNode.children as DOMNode[])}
          </ul>
        );
      }

      if (domNode.name === "li") {
        return (
          <li className="flex gap-2 items-center ">
            <Icons.PinkArrowMarker />
            {domToReact(domNode.children as DOMNode[])}
          </li>
        );
      }
    },
  };`
  Only first condition is getting replaced, can anyone help me with this?

**Comment by remarkablemark** [comment]
@Bkumar48 can you create a new issue?
