### ISSUE TITLE
version 5.0.1 cannot work with vite

### ISSUE THREAD

**Issue by InfiniteXyy** [remarkablemark/html-react-parser#1132]
## Expected Behavior

Should work with `vite`

## Actual Behavior

<img width="1439" alt="image" src="https://github.com/remarkablemark/html-react-parser/assets/26314308/bdae54e5-e6cd-4f1c-8506-9ed06f420127">

## Steps to Reproduce
1. Create a very simple react-ts starter project with `yarn create vite`
2. Install the latest version of `html-react-parser` with `yarn add html-react-parser`
3. Import and use it in `App.tsx`
4. run `npx vite build && npx vite preview`
5. There will be an `xxx is not a function` error

## Reproducible Demo

Stackblitz link: https://stackblitz.com/edit/vitejs-vite-grzmrj?file=package.json

## Environment

- Version: 5.0.1
- Browser: Chrome
- OS: MacOS

## Keywords

Module config

**Comment by remarkablemark** [comment]
I can confirm that the default export of the library in Vite is returning `undefined`: https://stackblitz.com/edit/vitejs-vite-k4quux?file=src%2FApp.tsx

I will prioritize a fix later today

**Comment by remarkablemark** [comment]
@InfiniteXyy just want to confirm, is this only happening on Stackblitz? I tried reproducing on CodeSandbox but it's working as expected: https://codesandbox.io/p/sandbox/html-react-parser-fg2jpw

**Comment by StFreve** [comment]
@remarkablemark You was looking into Dev. Something happens during the build. check it again in preview https://codesandbox.io/p/sandbox/html-react-parser-fg2jpw

**Comment by remarkablemark** [comment]
Thanks @StFreve, you're right that the same error happens when running `build` and `preview`.

**Comment by StFreve** [comment]
btw, I just fixed it locally for myself by replacing `export default HTMLReactParser.default` with `export default HTMLReactParser;` in `esm\index.mjs`

**Comment by remarkablemark** [comment]
Thanks @StFreve, I will open a PR for the fix soon

**Comment by remarkablemark** [comment]
Please review #1135

**Comment by remarkablemark** [comment]
Can someone help verify that the following release fixed the issue?

- https://github.com/remarkablemark/html-react-parser/pull/1136#issuecomment-1786221348

**Comment by StFreve** [comment]
@remarkablemark 5.0.3 fixed the issue for me. Thank you!

**Comment by ssi02014** [comment]
Cool!!
