### ISSUE TITLE
Parsing does not work on server side

### ISSUE THREAD

**Issue by rgavinc** [remarkablemark/html-react-parser#115]
Because of the changes made by [this commit](https://github.com/remarkablemark/html-react-parser/commit/1fb5ee2), parsing does not work on the server side. This is a problem for server-rendered React applications.

**Comment by remarkablemark** [comment]
Yes you're right @rgavinc. I was able to reproduce the issue in [Repl.it](https://repl.it/@remarkablemark/html-react-parser-115).

I'll revert commit 1fb5ee2.

**Comment by remarkablemark** [comment]
@rgavinc I released and published [`html-react-parser@0.8.1`](https://github.com/remarkablemark/html-react-parser/tree/v0.8.1):

```sh
# npm
npm i -S html-react-parser@0.8.1

# yarn
yarn add html-react-parser@0.8.1
```

**Comment by Gus19** [comment]
> Because of the changes made by [this commit](https://github.com/remarkablemark/html-react-parser/commit/1fb5ee2), parsing does not work on the server side. This is a problem for server-rendered React applications.

Hello, I have the same problem with 0.13 version, it's normal ?

**Comment by remarkablemark** [comment]
Issue should be fixed @Gus19. Can you provide a reproducible example using [Repl.it](https://repl.it/@remarkablemark/html-react-parser-SSR)?

And to note, script tags are not evaluated on the client-side. See [FAQ](https://github.com/remarkablemark/html-react-parser#are-script-tags-parsed).
