### ISSUE TITLE
Nothing is parsed after an iframe

### ISSUE THREAD

**Issue by noe** [remarkablemark/html-react-parser#1153]
## Expected Behavior

If there is more html after an iframe, it should be parsed.

## Actual Behavior

Anything after an iframe is ignored

## Steps to Reproduce

1. Parse a string that contains an iframe and any other element after it.

## Reproducible Demo

This is a reproducible example:

```js
function App() {
  function htmlToReact() {
    const html = `
<iframe src="https://www.youtube.com/embed/R4pKoJu6G3c?rel=0&playsinline=1"/>
<p>This is ignored</p>
    `;
    return HTMLReactParser(html);
  }

  return (
    <React.Fragment>
      {htmlToReact()}
    </React.Fragment>
  );
}
```

[Here as a fiddle](https://jsfiddle.net/s45wqxyr/11/).

## Environment

- Version: 5.0.6
- Platform: React 18
- Browser: Chrome Version 119.0.6045.105 (Official Build) (x86_64), Safari Version 17.0 (19616.1.27.211.1)
- OS: MacOS 14.0

## Keywords

iframe, ignored

**Comment by remarkablemark** [comment]
@noe The `<iframe>` in your HTML should not be a void element. If you properly close the `<iframe></iframe>`, it will work as expected. See https://jsfiddle.net/remarkablemark/jmp5otng/

**Comment by remarkablemark** [comment]
Closing as won't do
