### ISSUE TITLE
Issue after 5.0.9 update 

### ISSUE THREAD

**Issue by pongells** [remarkablemark/html-react-parser#1228]
## Expected Behavior

I should be able to use `Element`

## Actual Behavior

When I run my React app using Vite I get:

```
Uncaught SyntaxError: The requested module '/@fs/Users/.../node_modules/.vite/app/deps/html-react-parser.js?v=719515aa' does not provide an export named 'Element' (at list.tsx:6:31)
```

in list.tsx I have:

```
import { DOMNode, domToReact, Element } from "html-react-parser";
```

## Steps to Reproduce

Try to use `Element` after 5.0.9 update.

## Environment

- Version: 5.0.9
- Platform: Vite
- Browser: Chrome
- OS: MaxOs

**Comment by remarkablemark** [comment]
You're right @pongells, I caused a regression in the latest release. I was able to reproduce the issue in https://codesandbox.io/p/devbox/html-react-parser-fg2jpw

I will prioritize a fix ASAP

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1230#issuecomment-1861146591

**Comment by pongells** [comment]
Thanks @remarkablemark , works like a charm :)
