### ISSUE TITLE
Cannot Handle Microsoft Meeting Link

### ISSUE THREAD

**Issue by tragicmj** [remarkablemark/html-react-parser#1235]
## Expected Behavior

The microsoft meeting link should be parse without causing any error

## Actual Behavior

It doesn't gets parsed instead crashes.

## Steps to Reproduce

this is the content I am trying to parse

let content = `________________________________________________________________________________
Microsoft Teams meeting
Join on your computer, mobile app or room device
Click here to join the meeting<https://teams.microsoft.com/l/meetup-join/19:meeting_MWRmMzdmZWMtZjRmYS00NDA0LTgGMtMDI4YWZiOTUyZTNj@thread.v2/0?context={"Tid":"37c354b2-85b0-47f5-b222-07b48d774ee3","Oid":"e1a984f1-8d10-4b70-9b89-1d52d5b34f67"}>
Meeting ID: 375 123 950 776
Passcode: vmibUx
Download Teams<https://www.microsoft.com/en-us/microsoft-teams/download-app> | Join on the web<https://www.microsoft.com/microsoft-teams/join-a-meeting>
Or call in (audio only)
+44 20 3321 5208,,71547807#<tel:+4420332158,,715477#>   United Kingdom, London
Phone Conference ID: 715 458 06#
Find a local number<https://dialin.teams.microsoft.com/cef001b8-580b-4d45-a672-91ebd4f6f622?id=71547807> | Reset PIN<https://dialin.teams.microsoft.com/usp/pstnconferencing>
[https://fs.nhs.net/adfs/portal/logo/logo.jpg]
If you are planning to use Teams for clinical purposes, it is important to review usage with your local Information Governance and Clinical Safety teams to determine and adhere to best practice around patient data management.
Learn More<https://aka.ms/JoinTeamsMeeting> | Help<https://support.nhs.net/> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=e1a984f1-8d10-4b70-9b89-1d52d5b34f67&tenantId=37c354b2-85b0-47f5-b222-07b48d774ee3&threadId=19_meeting_MWRmMzdmZWMtZjRmYS00NDA0LTgxMGMtMDI4YWZiOTUyZTNj@thread.v2&messageId=0&language=en-US> | Legal<https://portal.nhs.net/Home/AcceptablePolicy>
________________________________________________________________________________

************************************************************************************** ******************************

This message may contain confidential information. If you are not the intended recipient please:
i) inform the sender that you have received the message in error before deleting it; and
ii) do not disclose, copy or distribute information in this e-mail or take any action in relation to its content (to do so is strictly prohibited and may be unlawful).
Thank you for your co-operation.

NHSmail is the secure email, collaboration and directory service available for all NHS staff in England. NHSmail is approved for exchanging patient data and other sensitive information with NHSmail and other accredited email services.

For more information and to find out how you can switch visit Joining NHSmail - NHSmail Support<https://support.nhs.net/article-categories/joining-nhsmail/>

`

**Comment by remarkablemark** [comment]
Thanks for opening this issue @tragicmj! Can you provide a reproducible example using [CodeSandbox](https://codesandbox.io/s/940pov1l4w)?

**Comment by tragicmj** [comment]
@remarkablemark here is the [code sandbox ](https://codesandbox.io/p/sandbox/clever-pine-59c8kh?file=%2Fsrc%2Findex.js%3A42%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqdidktb00063b5w0gka8muo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqdidktb00023b5w1q1d0vv3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqdidktb00033b5whyh90uvc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqdidktb00053b5w1zoypuw6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqdidktb00023b5w1q1d0vv3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdidktb00013b5wva16v1jn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A42%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A42%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clqdidktb00023b5w1q1d0vv3%2522%252C%2522activeTabId%2522%253A%2522clqdidktb00013b5wva16v1jn%2522%257D%252C%2522clqdidktb00053b5w1zoypuw6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdidktb00043b5wwujq3plk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqdidktb00053b5w1zoypuw6%2522%252C%2522activeTabId%2522%253A%2522clqdidktb00043b5wwujq3plk%2522%257D%252C%2522clqdidktb00033b5whyh90uvc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqdidktb00033b5whyh90uvc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by remarkablemark** [comment]
@tragicmj The error is coming from trying to parse `<tel>`, which is an invalid HTML element. My recommendation is to either:

1. Clean the HTML and remove invalid HTML elements, or
2. Use [dangerouslySetInnerHTML](https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html)

See updated [CodeSandbox](https://codesandbox.io/p/sandbox/html-react-parser-1235-lqmyd5) for approach 2

**Comment by asd-ez** [comment]
The same for me, I used 

> 1. Clean the HTML string and remove invalid HTML elements

```js
'html_string'.replace(/<tel:(.+?)>/g, "tel:$1")
```
