### ISSUE TITLE
Method transform has wrong current index

### ISSUE THREAD

**Issue by sx-motive** [remarkablemark/html-react-parser#1259]
Hi, I probably misunderstood something, but I didn't find any answers or related problems, so please help to make this clear 

## Expected Behavior

```javascript 
parse('<p>first</p><span>second</span><div>third</div>', {
  transform: (reactNode, domNode, index) => {
    console.log(index);
    return reactNode as string;
   },
})
 ```
 **output: 0, 1, 2**

## Actual Behavior

**output: 0, 1, 0, 2**

## Steps to Reproduce

code in _Expected Behavior_

## Environment

- Version: 5.0.11

**Comment by remarkablemark** [comment]
@sx-motive can you add `domNode` to your log and provide your output here?

**Comment by remarkablemark** [comment]
This may not fix your issue, but I released a version that passed index as the 2nd argument in `replace`:

- https://github.com/remarkablemark/html-react-parser/pull/1261#issuecomment-1885718746

**Comment by sx-motive** [comment]
@remarkablemark sure, here is output with `domNode`

![Screenshot 2024-01-12 132554](https://github.com/remarkablemark/html-react-parser/assets/54843147/18d2905f-9f23-4acd-88fd-bacc3e6f09d6)

**Comment by remarkablemark** [comment]
Thanks @sx-motive. So it looks like the node index is correctly resetting itself when the parser is traversing the nested children:

```html
<p><!-- 0 -->
  first<!-- 0 -->
</p>
<span><!-- 1 -->
  second<!-- 0 -->
</span>
<div><!-- 2 -->
  third<!-- 0 -->
</div>
```

Let me know if that makes sense.

**Comment by sx-motive** [comment]
@remarkablemark yes, now I see how this works, thanks for answers.
