### ISSUE TITLE
Parser completely removes body elements if html string has open <html> and <body> tags, but does not have close </body> and </html> tags

### ISSUE THREAD

**Issue by sanex3339** [remarkablemark/html-react-parser#126]
## Expected Behavior

Parser should try to keep all existing html tags if html string has open <html> and <body> tags, but does not have close </body> and </html> tags

## Actual Behavior

Parser completely removes all body elements if html string has open <html> and <body> tags, but does not have close </body> and </html> tags

## Steps to Reproduce

Just try to parse following html string:
```
 <html>
        <body>
          <h1 style="font-family: Arial;">
            html-react-parser
          </h1>
```

## Reproducible Demo

https://jsfiddle.net/rxzudvmf/

## Environment

- Version: 0.9.1
- Platform: Mac OS
- Browser: Chrome 77

**Comment by sanex3339** [comment]
Looks like a problem of html-dom-parser

**Comment by remarkablemark** [comment]
[`html-react-parser@0.9.2`](https://github.com/remarkablemark/html-react-parser/releases/tag/v0.9.2) has been released and published:

```sh
# update with npm
npm i -S html-react-parser@0.9.2

# or with yarn
yarn add html-react-parser@0.9.2
```

Let me know if this resolves the issue for you @sanex3339.
