### ISSUE TITLE
Validate props beforing passing the props object to the element

### ISSUE THREAD

**Issue by yaman3bd** [remarkablemark/html-react-parser#1266]
## Problem
I'm working with `HTML/JS` code fetched from a CMS. if the code contains broken or invalid attributes, it will leads to an error:
```
InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'javascript"' is not a valid attribute name.
```
here is an example code that has the error:
```html
<script type="text/
<!--Start of JS code-->
<script type="text/javascript">
//JS code goes here
</script>
<!--Start of JS code-->
<!--Start of CSS code-->
<style>
/*CSS code goes here*/
</style>
<!--End of CSS code-->
```
## Suggested Solution
validate `attributes/props` before passing them to the `Element`, so only valid props will be in the final result. 

## Keywords

React.cloneElement, attribute validation, InvalidCharacterError, CMS, parsing

**Comment by remarkablemark** [comment]
Hi @yaman3bd, this library does not fix invalid HTML. Feel free to use another library to fix invalid HTML before passing it into `html-react-parser`.

**Comment by yaman3bd** [comment]
thanks for the replay, I tried `sanitize-html` and `dompurify` both did not fix the problem, I do not want to check against XSS attacks, I want only to check if the HTML syntax is valid or not. like there is no missing closing tag, no wrong att name/value, or any other possible syntax errors. what do you recommend to use in this case? or how would you handle such issue?

**Comment by remarkablemark** [comment]
@yaman3bd there should be an npm package that could do what you're looking for. I don't know any on top of my head, although I was going to suggest `sanitize-html` but it seems to not work for your use-case.
