### ISSUE TITLE
How to get string representation of the domnode returned by replace option?

### ISSUE THREAD

**Issue by JMA12** [remarkablemark/html-react-parser#127]
## Environment

- Version:
- Platform:
- Browser:

**Comment by remarkablemark** [comment]
Do you mind clarifying your question? When you mention _string representation_, do you mean the HTML string or something else?

Also, does this [replace example](https://repl.it/@remarkablemark/html-react-parser-replace-example) help in any way?

**Comment by remarkablemark** [comment]
Closing the issue because there hasn't been a response.

**Comment by JMA12** [comment]
> Closing the issue because there hasn't been a response.

Uhmm sorry for the late response.

I am asking on how to get HTML string representation of the domnode returned in replace because what I get from replace return is a dom object

**Comment by remarkablemark** [comment]
Hey @JMA12, unfortunately once the string is parsed, there isn't an easy way to stringify the DOM node unless you create a DOM node to string function. Let me know if this answers your question.

**Comment by JMA12** [comment]
Uhmm, in what structure is the replace method throwing?? Is it a dom object??

Just want to know for me to search for an appropriate converter.

Thanks.

**Comment by remarkablemark** [comment]
The structure is documented in the [README](https://github.com/remarkablemark/html-react-parser#replacedomnode) (see [Repl.it](https://repl.it/@remarkablemark/html-react-parser-127)).

**Comment by remarkablemark** [comment]
Closing issue since I believe I have answered your question. Feel free to reopen if there are further questions.
