### ISSUE TITLE
How to resize/style the HTML content? 

### ISSUE THREAD

**Issue by Iven2132** [remarkablemark/html-react-parser#1287]
## Question

How to resize/style the HTML content? for example, I want to make the HTML content small. currently, when I try to wrap parse(htmlContent) into a div and give it height and width it's not making the HTML content small. How to fix it? 

```
   <div>
            <h1>HTML Content</h1>
            <div style={{ width: '50%' }}>
                {parse(htmlContent)}
            </div>
        </div>
```

**Comment by remarkablemark** [comment]
@Iven2132 can you try [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale)?

**Comment by Iven2132** [comment]
@remarkablemark Hi, Not working 

```
import React, { useState, useEffect } from 'react';
import parse from 'html-react-parser';

function ResizableHTMLContent() {
  const [htmlContent, setHtmlContent] = useState('');

  useEffect(() => {
    fetch('/file.txt') 
      .then(response => response.text())
      .then(html => {
        setHtmlContent(html);
      })
      .catch(error => {
        console.error('Error fetching HTML content:', error);
      });
  }, []);

  return (
    <div>
      <h1>HTML Content</h1>
      <div style={{ scale: 1 }}>
        {parse(htmlContent)}
      </div>
    </div>
  );
}

export default ResizableHTMLContent;

```

**Comment by remarkablemark** [comment]
If you want it smaller, you need to use a scale smaller than `1` (e.g.,` 0.5`)

**Comment by Iven2132** [comment]
@remarkablemark I set it to 0.5 and also 0.7 it's not changing its size, please help🙏

**Comment by Iven2132** [comment]
@remarkablemark Hi, I still couldn't figure out the problem I posted on Stackoverflow no one replied can you please help me, Mark?

**Comment by remarkablemark** [comment]
Can you share a [CodeSandbox](https://codesandbox.io/s/940pov1l4w) or [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/) of your issue?

**Comment by Iven2132** [comment]
@remarkablemark Yes, sure here is the [CodeSandBox](https://codesandbox.io/p/devbox/w9n5ny?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls3hpxds00063b6g3jbqrwob%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls3hpxds00023b6girjtx1y4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls3hpxds00033b6g81npr2td%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls3hpxds00053b6gna6awajg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.844156494209365%252C46.155843505790635%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls3hpxds00023b6girjtx1y4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3hpxds00013b6ggnel1108%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls3hpxds00023b6girjtx1y4%2522%252C%2522activeTabId%2522%253A%2522cls3hpxds00013b6ggnel1108%2522%257D%252C%2522cls3hpxds00053b6gna6awajg%2522%253A%257B%2522id%2522%253A%2522cls3hpxds00053b6gna6awajg%2522%252C%2522activeTabId%2522%253A%2522cls3hsj2l009e3b6gfuic3vnn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cls3hsj2l009e3b6gfuic3vnn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fquestions%252F77922248%252Ftechnical-seo-with-python%2522%257D%255D%257D%252C%2522cls3hpxds00033b6g81npr2td%2522%253A%257B%2522id%2522%253A%2522cls3hpxds00033b6g81npr2td%2522%252C%2522activeTabId%2522%253A%2522cls3hsgto007a3b6g8bbk26bc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3hs8od003k3b6gn0ooerjf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls3hs8v0000ldlh06nkidog2%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cls3hsgto007a3b6g8bbk26bc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by remarkablemark** [comment]
It says `Sandbox not found`:

![Screen Shot 2024-02-01 at 1 28 01 PM](https://github.com/remarkablemark/html-react-parser/assets/10594555/f5995b59-7b80-4f00-9951-6525348e4be9)

Did you fork and save the sandbox?

**Comment by Iven2132** [comment]
@remarkablemark Any idea how to fix it?

**Comment by Iven2132** [comment]
@remarkablemark Hi Mark, Do you need my code Github repo?
