### ISSUE TITLE
Resolution error when using TypeScript with `moduleResolution` set to  `node16` or `nodenext`

### ISSUE THREAD

**Issue by wojtekmaj** [remarkablemark/html-react-parser#1305]
## Expected Behavior

html-react-parser to resolve correctly when using TypeScript with `moduleResolution` set to  `node16` or `nodenext` (effectively: in pure ESM environment). 

## Actual Behavior

html-react-parser is not resolved correctly:

https://arethetypeswrong.github.io/?p=html-react-parser%405.1.2

This also causes the types to be non-functional in VSCode:

<img width="331" alt="image" src="https://github.com/remarkablemark/html-react-parser/assets/5426427/c691457f-5e82-44e2-adae-7f8649ffb7ec">

## Steps to Reproduce

Create a project using TypeScript with `moduleResolution` set to  `node16` or `nodenext`.
Create a file with the following content:

```ts
import parse from 'html-react-parser';
```

you'll already see, when you hover over `parse` bit, that types are not loaded correctly.

## Environment

- Version: 5.0.7
- Platform: Node.js
- Browser: not applicable
- OS: macOS Sonoma 14.2.1

## Keywords

Relates to https://github.com/remarkablemark/html-dom-parser/issues/669

**Comment by remarkablemark** [comment]
Can you verify if this issue is resolved in the release?

- https://github.com/remarkablemark/html-react-parser/pull/1311#issuecomment-1939643296

Are the Types Wrong looks good: https://arethetypeswrong.github.io/?p=html-react-parser%405.1.4

**Comment by wojtekmaj** [comment]
Hi @remarkablemark, thanks for this. It's a definite improvement since the types are now working correctly. But (unlike in `html-dom-parser`, which doesn't use any imports beyond `index.(m)js` files), module resolution inside is still broken, as extensionless imports are being used.

I'm more than happy to fix that, but I believe we'd like to have an architectural decision made in https://github.com/remarkablemark/html-dom-parser/pull/671 to avoid breaking changes :)

**Comment by remarkablemark** [comment]
Makes sense, we can discuss there

**Comment by Hotell** [comment]
wondering why was this closed ? 

facing the same issue

```
"html-react-parser": "5.1.10",

"moduleResolution": "Node16",
```

<img width="1270" alt="image" src="https://github.com/remarkablemark/html-react-parser/assets/1223799/c191c32d-1e02-4a25-83d7-5e22d2410bd5">

**Comment by remarkablemark** [comment]
@Hotell do you mind opening a new issue?
