### ISSUE TITLE
Type of `parse` is `any`

### ISSUE THREAD

**Issue by DreierF** [remarkablemark/html-react-parser#1313]
## Expected Behavior

The `parse` function exported from `html-react-parser` should have a proper type.

## Actual Behavior

Since 5.1.4 the type is any, which basically turns off type checking for the parameters and any processing that happens on the returned value. This used to work in previous versions.

## Steps to Reproduce

```
import parse, { Element } from "html-react-parser";

const html = ...;

const parsed = parse(html, {
    // ^ parse has type any now
  replace(domNode) {
    //      ^ This type was correctly inferred in previous versions
   ...
  },
});
```

## Reproducible Demo

[Reproduction in Codesandbox](https://codesandbox.io/p/devbox/html-react-parser-forked-2pd922?file=%2Fsrc%2Findex.tsx%3A23%2C16-23%2C21)

## Environment

- Version: 5.1.4

## Keywords

types, #1305

**Comment by remarkablemark** [comment]
Thanks @DreierF, this is a regression caused in #1310. I'll look into a fix later tonight.

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1315#issuecomment-1942897156
