### ISSUE TITLE
Custom Self Closing Tags treat following text as children data

### ISSUE THREAD

**Issue by sowhatdoido** [remarkablemark/html-react-parser#132]
**Expected Behavior:**
Self closing tags are treated as a tag with no data in it:
`<Example /> should equal <Example></Example>
`

**Actual Behavior:**
Library doesn't detect custom self closing tags, and is treating them like tags that have never been closed:
`<Example /> is treated like <Example>
`

**Steps to reproduce:**
- Run parser with a replace option using this text: `This text has a self closing tag <Example /> for you to see.`
- Replace function should just log using the following: `console.log('test', type, name, children);`
- See in console:
![image](https://user-images.githubusercontent.com/1973601/69222913-4360b080-0b2f-11ea-9675-d027231e557b.png)
- Result shows that the Example tag has a children object with the trailing text in the data property.
- Change the text to have a closing tag: `...<Example></Example>...`
- Results now show that the Example tag doesn't have a child:
![image](https://user-images.githubusercontent.com/1973601/69223149-a8b4a180-0b2f-11ea-93d4-5cf29858dce2.png)

**Comment by remarkablemark** [comment]
Thanks for opening the issue @sowhatdoido

I'm a bit confused, shouldn't a self-closing tag have no or empty children? In other words, shouldn't this be expected behavior?

I've tried to reproduce this in the following repls:
- [html-react-parser server](https://repl.it/@remarkablemark/html-react-parser-132-1)
- [html-dom-parser server](https://repl.it/@remarkablemark/html-react-parser-132-2)
- [html-react-parser client](https://repl.it/@remarkablemark/html-react-parser-132-3)

On a side note, this may be related to [html-dom-parser](https://github.com/remarkablemark/html-dom-parser).

Is this happening on the client (browser) or the server (Node.js)?

**Comment by sowhatdoido** [comment]
Thanks for your time @remarkablemark! This is happening to me on a browser, not nodejs.

A self closing tag describes a tag that has no children, but has the unique ability to close without having a separate tag to define the end. Common examples of this in standard html format are:
```
<br />
<hr />
<img />
<input />
```
to name a few.


In my case, when I try to parse a self closing tag and replace it with a React component, I expect children to be null, but I'm actually getting everything that follows the self closing tag as the child. In other words:
```
hello there <br /> my friend
```
is parsing as if I wrote
```
hello there <br> my friend </br>
```

which is incorrect.

You're absolute right, it could be related to html-dom-parser; I'll try out an example with to see if the problem stems from there and report back my findings. I'll also include a codebox of what I'm trying to explain above as well so you can better see what I mean.

**Comment by sowhatdoido** [comment]
You can actually see the problem if you modify your first repl:

https://repl.it/repls/AstonishingWhisperedTrapezoids

In theory, both those lines should be the same console logs, but if you add text before and after the tags, you'll notice the tag in the first console.log has a child object and the second one doesn't:


Correct:
![](https://i.gyazo.com/da23a5a4812e02c21b2accc54fbbcd20.png)
Incorrect:
![](https://i.gyazo.com/89a1a95e46d78a5a2994a924d3153b71.png)

**Comment by sowhatdoido** [comment]
@remarkablemark,

It looks like you were right in that the problem is with html-dom-parser: It appears that you are [creating the node list from a string](https://github.com/remarkablemark/html-dom-parser/blob/eceb8f5addbc5c682329735533bf74227c72dd58/lib/domparser.js#L117) by using `template`, which doesn't seem to support self closing tags (I assume because that's not considered valid markup in standard html unless it's whitelisted?). As a result:

![](https://i.gyazo.com/57ffb65220582144d0cf92d0453d3990.png)

I would still argue that this is incorrect within the scope of this library since[ React/JSX supports self-closing tags](https://reactjs.org/docs/jsx-in-depth.html).

Not sure if you want to support this use case or not.

**Comment by remarkablemark** [comment]
Thanks for looking into this @sowhatdoido

So now that we've identified where this is coming from, I don't think that parsing JSX in HTML is a feature that `html-dom-parser` supports.

Like you mentioned, `<Example />` isn't valid HTML markup so perhaps what you're looking for is more of a JSX string to React elements parser rather than an HTML string to React elements parser? The former is technically what babel parser is doing.

**Comment by sowhatdoido** [comment]
Yeah I think that's fair, and thus why I was asking if whether or not you think you wanted to support this within the context of your library.

I found a work around for this specific use case, though it definitely feels suboptimal. Essentially, I'd perform a regex match on the string I'm trying to parse and format it to a closed component if it doesn't match a void element... perhaps something like this (I haven't fleshed out all the details yet):
`<(?!area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)([A-z]+) (.*) \/>`

Please feel free to comment with a decision and close out the issue if you feel JSX shouldn't be supported here.

**Comment by remarkablemark** [comment]
Yes, I don't believe this library will be supporting custom JSX elements here. I'll be closing the issue, feel free to reopen or open a new issue if you encounter a new problem @sowhatdoido

**Comment by yougotashovel** [comment]
@sowhatdoido  Would you mind sharing how you implemented your workaround?  

I'm currently having the same issue parsing custom html elements with no closing tags

**Comment by joneldiablo** [comment]
I have the same problem, I have some components wich I need put as string like: `"<Component />"` if I use like this not works, only `"<Component></Component>"`

**Comment by sowhatdoido** [comment]
For anyone looking for a solution to this, per my conversation with the author and unless he changes his mind otherwise: this  is an HTML to React parser, not a JSX to React parser, a subtle but important difference. Your tags are being auto closed by the browser itself, not something the author's code is doing, and you can override it by using replace if you'd like but in my experience dealing with regex and allow/block lists just introduce more of a headache in the long run than necessary.

---

The way I ended up solving my problem was just respecting the author's scope and switching to a different library, specialized in JSX to React parsing: https://github.com/TroyAlford/react-jsx-parser. This library deals specifically in taking JSX as a string and converting it into something usable on the page, such as entering a custom `<MyComponent />` in a CMS. 

Additionally you can bind javascript variables to the renderer, so it lets your authors do custom formatting like: `This costs: <PriceFormatter>{price}</PriceFormatter> as shown.`, where `PricerFormatter` is a custom component and `price` was bound to the parser for this instance.

**Comment by remarkablemark** [comment]
You summarized it nicely @sowhatdoido and thanks for sharing your alternative solution!

**Comment by phillsv87** [comment]
I used a Regex. It works with custom components too.

``` js
import parse from 'html-react-parser';

const html=`
    <div>
        <div>If you're not first</div>
        <div/>
        <div>you're last</div>
        <div/>
        <div>- Ricky Bobby</div>
    </div>
`
const selfClosingReg=/<(\w+)([^>/]*)\/\s*>/g;

html=html.replace(
    selfClosingReg,
    (all,tagName,content)=>(
        `<${tagName}${content}></${tagName}>`
    )
);

console.log(html)

const doSomethingWithMe=parse(html)

```

``` html
<div>
    <div>If you're not first</div>
    <div></div>
    <div>you're last</div>
    <div></div>
    <div>- Ricky Bobby</div>
</div>
```
