### ISSUE TITLE
Version 5.1.5 - multiple versions of @types/react causes typescript build errors

### ISSUE THREAD

**Issue by captain-igloo** [remarkablemark/html-react-parser#1320]
From version 5.1.5 I get errors building my typescript project due to multiple versions of @types/react. I'm not sure if this is a problem with html-react-parser or with @types/react.

See https://github.com/remarkablemark/html-react-parser/commit/78b7a8e8a52b23676a5d86ef60ee9c57683839e3

## Expected Behavior

Should build correctly, possibly should have dependency on @types/react version ^18.2.55 instead of 18.2.55

## Actual Behavior

```
node_modules/@types/react/index.d.ts:4127:14 - error TS2300: Duplicate identifier 'ElementType'.

4127         type ElementType = string | React.JSXElementConstructor<any>;
                  ~~~~~~~~~~~

  node_modules/html-react-parser/node_modules/@types/react/index.d.ts:4127:14
    4127         type ElementType = string | React.JSXElementConstructor<any>;
                      ~~~~~~~~~~~
    'ElementType' was also declared here.

node_modules/@types/react/index.d.ts:4141:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

4141         type LibraryManagedAttributes<C, P> = C extends
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/html-react-parser/node_modules/@types/react/index.d.ts:4141:14
    4141         type LibraryManagedAttributes<C, P> = C extends
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.

node_modules/html-react-parser/node_modules/@types/react/index.d.ts:4127:14 - error TS2300: Duplicate identifier 'ElementType'.

4127         type ElementType = string | React.JSXElementConstructor<any>;
                  ~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:4127:14
    4127         type ElementType = string | React.JSXElementConstructor<any>;
                      ~~~~~~~~~~~
    'ElementType' was also declared here.

node_modules/html-react-parser/node_modules/@types/react/index.d.ts:4141:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

4141         type LibraryManagedAttributes<C, P> = C extends
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:4141:14
    4141         type LibraryManagedAttributes<C, P> = C extends
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.
```

## Steps to Reproduce

git clone git@github.com:captain-igloo/html-react-parser-bug.git
cd html-react-parser-bug
npm ci
npm run build

## Reproducible Demo

https://github.com/captain-igloo/html-react-parser-bug

## Keywords

@types/react

**Comment by remarkablemark** [comment]
@captain-igloo thanks for the find! Would you like to open a PR for the fix? I think your suggestion to use `^18.2.55` sounds good

**Comment by remarkablemark** [comment]
PR for fix: #1321

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1322#issuecomment-1951583324

**Comment by captain-igloo** [comment]
Thanks @remarkablemark , it works now.

**Comment by andrucz** [comment]
@remarkablemark why is `@types/react` a dependency rather than a dev dependency?

We have a few React apps that work as plugins of a legacy application that provides React 16 at runtime, so we can use 5.1.4 only.

**Comment by remarkablemark** [comment]
@andrucz the reason is because ESM types were not working when it was a devDependency. See #1314

I can make this a peerDependency if you think it's better for consumers to install their own version of `@types/react`
