### ISSUE TITLE
Possible to render react component based on data attribute?

### ISSUE THREAD

**Issue by steeevio** [remarkablemark/html-react-parser#133]
Hi, 

I'm trying to parse html that contains several divs with a class of sjevComponent. These have different data attributes such as data-type="Logo" which I would like to use to call a `<Logo/>` react component. Is this possible? I'm currently rendering a `<logo>` element rather than generating a react component.

`	render(){

		let html = this.props.pageContent;
		let options =   {
			replace: domNode => {
			    if (domNode.attribs && domNode.attribs.class === 'sjevComponent') {
			    	console.dir(domNode, { depth: null });

			    	let src = domNode.attribs['data-src']
			    	let element = domNode.attribs['data-type']

			    	return React.createElement(element, { src: src });
			    }  
			}
		}

    	return (
    		<div>
		      	<Content>
		      		{ parse(html, options )}
		      	</Content>
		</div>
    	)
	}`

**Comment by steeevio** [comment]
Ah never mind, I just needed to conditionally return a react component.

**Comment by remarkablemark** [comment]
@steeevio It seems like you've answered your own question. If you don't have any other issue, would you kindly close the issue? Thanks!
