### ISSUE TITLE
Typescript import errors

### ISSUE THREAD

**Issue by KiranMohan** [remarkablemark/html-react-parser#134]
Is the typescript definition correct? Only the below import syntax worked for me.
`import * as HTMLReactParser from 'html-react-parser';`
But this gives a build error
`Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("app/node_modules/html-react-parser/index")' has no compatible call signatures`

## Expected Behavior
Compilation goes fine without error.  
No errors in browser console at runtime.

## Actual Behavior
Compilations errors reported. 
Runs fine in browser

## Steps to Reproduce
see above

## Environment

- Version: 0.10.0
- Platform: Windows
- Browser: Chrome 79.0.3945.88

**Comment by chpio** [comment]
`replace` is also mandatory, you can't pass in an `undefined`: `{replace: undefined}`

**Comment by remarkablemark** [comment]
@KiranMohan sorry for the late response but as @chpio mentioned, you should be able to import the default export:

```ts
import HTMLReactParser from 'html-react-parser';
```

You can see this is the recommended approach in the [README](https://github.com/remarkablemark/html-react-parser#usage) or interact with the [CodeSandbox](https://codesandbox.io/s/html-react-parser-typescript-0g0ct) demo.

---

@chpio The 2nd argument should be [optional](https://github.com/remarkablemark/html-react-parser/blob/v0.10.0/index.d.ts#L23). But I could technically loosen the strict checking of `replace` if an empty object is passed.

**Comment by chpio** [comment]
> @chpio The 2nd argument should be optional.

yeah it is, but you can not pass in `replace` conditionally, just the whole options object.

**Comment by remarkablemark** [comment]
@chpio I see, would it be better if I made `replace` optional in the object?

**Comment by remarkablemark** [comment]
@chpio I made `replace` optional in the object.

See [`html-react-parser@0.10.1`](https://github.com/remarkablemark/html-react-parser/tree/v0.10.1):

```sh
# npm
npm i -S html-react-parser@0.10.1

# yarn
yarn add html-react-parser@0.10.1
```

**Comment by remarkablemark** [comment]
I will be closing this issue.

If there are additional questions, feel free to reopen or create a new issue @KiranMohan @chpio
