### ISSUE TITLE
How do I import this into Typescript?

### ISSUE THREAD

**Issue by scottschafer** [remarkablemark/html-react-parser#138]
I can import this into my Typescript file like this:
```
import parse from 'html-react-parser';
```

But then parse is undefined.

This is the insane way I got this to work:
```
import * as parseHtml from 'html-react-parser';
import HTMLReactParser from 'html-react-parser';
const parse = (parseHtml as any) as (typeof HTMLReactParser);
```

So then `parse('<h1>Hello world</h1>')` works as expected. What's the less insane way?

**Comment by remarkablemark** [comment]
This seems similar to #134

What's your `tsconfig.json` like? Here's a [CodeSandbox](https://codesandbox.io/s/html-react-parser-typescript-0g0ct) of the parser working in TypeScript

**Comment by scottschafer** [comment]
Here's my tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "incremental": true,
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "target": "ES5",
    "skipLibCheck": true,
    "downlevelIteration": true,
    "jsx": "react",
    "lib": [
      "es6",
      "dom"
    ],
    "typeRoots": ["node_modules/@types/"],
    "rootDirs": [
      "./src/app/"
    ],
    "types": [
      "jquery",
      "angular",
      "angular-ui-router",
      "angular-mocks",
      "node",
      "jasmine",
      "react"
    ],
    "baseUrl": ".",
    "paths": {
      "@app/*": ["src/app/*"],
      "@src/*": ["src/*"],
      "@models/*": ["src/app/data/models/*"],
      "@stores/*": ["src/app/data/stores/*"]
    }
  },
  "exclude": [
    "node_modules",
    "bower_components",
    "build"
  ],
  "include": [
    "src/**/*"
  ],
}
```
When I try `import parse from 'html-react-parser';` I get this at runtime:
`TypeError: html_react_parser_1.default is not a function`

Not sure what's going on. I'll stick with my solution for now.

**Comment by remarkablemark** [comment]
In `"compilerOptions"`, can you try adding:
```
"module": "commonjs"
```
and/or:
```
"esModuleInterop": true
```

**Comment by scottschafer** [comment]
Unfortunately, neither option works for me. If I make both changes, other imports fail. I would love to find the right solution, but my solution works for now. Thanks for the library and the response!

**Comment by remarkablemark** [comment]
Sounds good, thanks for trying! I'll be closing the issue.
