### ISSUE TITLE
inline style parser not working.

### ISSUE THREAD

**Issue by renszzzzzzz** [remarkablemark/html-react-parser#139]
Hey all, 

It seems that not all tags with inline styling (string) are correctly converted. The correct result is provided, when the style is put on the image tag instead of the figure tag. However for this project it needs to stay on the figure tag.

This is how I implemented the library:

```
import React, { Component } from 'react'
import parse from 'html-react-parser'; 

export class client extends Component {
    render() {
        return (
            <div>
                {parse(item.details)}
            </div>
        )
    }
}
```

## Expected Behavior

```
<figure className="image image_resized" style={{width: '54.26%'}}>
<img src="...amazon.jpg" /></figure>
```

## Actual Behavior

`<figure class="image image_resized" style="width: 54.26%;"><img src="...amazon.jpg"></figure>`

## Environment

- Version:  ^0.10.1
- Platform: react 
- Browser: Microsoft Edge (chromium)

**Comment by remarkablemark** [comment]
@renszzzzzzz Can you provide a reproducible example using [Repl.it](https://repl.it/@remarkablemark/html-react-parser)?

**Comment by renszzzzzzz** [comment]
@remarkablemark, thank you for your quick response. Created the example and it seems to output correctly in the console, but not in the dom.

However the changes are not reflected as you can see in this fiddle: https://jsfiddle.net/renszzzzzzz/7f8zo3ux

log shows the changes: 
![image](https://user-images.githubusercontent.com/2360975/74612331-539a1480-50b9-11ea-944d-dc08efb87c20.png)

DOM doesn't reflect the changes on figure:
![image](https://user-images.githubusercontent.com/2360975/74612344-6dd3f280-50b9-11ea-98e3-28690fafe3c6.png)

**Comment by remarkablemark** [comment]
I'm a little bit confused. Isn't this what you want?

You would only find `style={{ width: '54.26%' }}` in JSX. But in the DOM, `style="width: 54.26%` is expected and valid here. Am I missing something?

**Comment by renszzzzzzz** [comment]
Hey @remarkablemark. You're correct, I found the problem which wasn't related to your code. Thanks for the quick response
