### ISSUE TITLE
Error: img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by poacher2k** [remarkablemark/html-react-parser#14]
Hi!

Great plugin, really think this is going to be helpful for what I'm working on.

I noticed that parsing any `img`-element causes the above error. This may also apply to any element that never should have child elements.

A temporary workaround is to use something like this:

```
const parserConfig = {
	replace: domNode => {
		if(domNode.type === DOM_TYPE_TAG && domNode.name === 'img') {
			return <img src={domNode.attribs.src} alt={domNode.attribs.alt} className={domNode.attribs.class} />;
		}
	}
};
```

**Comment by remarkablemark** [comment]
Thanks for letting me know. Do you have an example so I can reproduce this error?

**Comment by poacher2k** [comment]
Hi!
You can reproduce this with the following:
`ReactDOM.render(Parser('<div><img src="" alt=""/></div>'), document.getElementById('root'));`

**Comment by poacher2k** [comment]
Awesome, thank you!

**Comment by remarkablemark** [comment]
@poacher2k Thanks for the example. I've looked into the bug and made a fix in #16.

Try `npm update html-react-parser` or `npm install html-react-parser@0.0.4` and let me know if this removes the error for you.

**Comment by poacher2k** [comment]
That fixed it, thanks again! Glad to see you also added checks for other void elements!

**Comment by remarkablemark** [comment]
Great to hear and you're very welcome! 👍

**Comment by vidit1** [comment]
I am still facing the issue and npm install html-react-parser@0.0.4  code is not updated in this version.

**Comment by remarkablemark** [comment]
@vidit1 Can you confirm that you installed the `latest` version?

```sh
npm i html-react-parser@latest

# or
npm i html-react-parser@0.4.1
```

Then verify by doing:
```sh
npm ls html-react-parser
```

**Comment by blueskysmart** [comment]
@remarkablemark I updated the latest version html-react-parser and still face this issue. My <img> element  is inside a material-ui component.
`<Drawer
                    open={this.state.open}
                    docked={false}
                    openSecondary={true}
                    onRequestChange={this.onRequestChange}
                    width="50%"
                >
                    <div className="alert" role="alert">
                                <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" className="d-inline-block align-top" alt="">
                                    Bootstrap
                                </img>
                    </div>
                </Drawer>`

**Comment by poacher2k** [comment]
@blueskysmart : You have `Bootstrap` inside your `img`-tag. As the error says, `img` is a void element, and cannot have any children. Changing your code to this should solve the issue:
`<Drawer> <div className="alert" role="alert"> <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" className="d-inline-block align-top" alt="" /> </div> </Drawer>`

**Comment by remarkablemark** [comment]
@blueskysmart The comment made by @poacher2k is correct. You can see the reproduction of this error in this [fiddle](https://jsfiddle.net/remarkablemark/Lrrbsy72/).

**Comment by blueskysmart** [comment]
Okie, I see. Thank you.

**Comment by cipiripper** [comment]
This error comes up also if you only try to parse this: 
```<img src="img.jpg".>```

To make it work, wrap it in a div:

```
<div>
<img src="img.jpg".>
</div>
```

**Comment by Sshetty2** [comment]
I was running into this issue because I was trying to add children to an img tag...
