### ISSUE TITLE
String text with less than greater than sign are treated as tags. (eg. 4<y<8)

### ISSUE THREAD

**Issue by kuldeep21** [remarkablemark/html-react-parser#1404]
https://codesandbox.io/p/devbox/html-react-parser-demo-forked-cv8r3n?embed=1&file=%2Fpages%2Findex.js&showConsole=true

##Expected Behavior##

It should parse complete text 4<y<8

**Comment by remarkablemark** [comment]
@kuldeep21 I believe this is expected behavior of `html-dom-parser`. Could you replace the tags with HTML entities? For example:

```html
4&lt;y&lt;8
```
