### ISSUE TITLE
Readme incorrectly states that script tags are processed

### ISSUE THREAD

**Issue by nwalters512** [remarkablemark/html-react-parser#142]
The readme claims that this library parses `<script>` tags:

> Are `<script>` tags parsed?
> Although `<script>` tags and their contents are rendered on the server-side, they're not evaluated on the client-side. See #98.

However, it looks like #109 removed that functionality. This is unfortunate, as there's still value in processing `<script>` tags in server-side environments like Next.js's `_document.js` component.

Either the Readme should be updated to reflect this, or (ideally) support for `<script>` tags should be added again to support more advanced use cases.

**Comment by remarkablemark** [comment]
It was added back in #116, please update to the latest version or `0.8.1`

**Comment by nwalters512** [comment]
Apologies, that PR didn't come up in my searches! Thanks for the quick response.
