### ISSUE TITLE
Question: Replace node type text by a React Component

### ISSUE THREAD

**Issue by josue-suarez-wt** [remarkablemark/html-react-parser#1428]
## Question

Is it possible to replace a domNode type text by a React Component? For example

`
      if (domNode.type === 'text') {
        return <Text field={{ ...fieldsContent, value: domNode.data }} style={{ color: 'red' }} />;
`

## Keywords

html-react-parser
react component
text

**Comment by remarkablemark** [comment]
@josue-suarez-wt yes, this is possible and a valid use-case of this library. See [README](https://github.com/remarkablemark/html-react-parser/tree/v5.1.10#replace)

**Comment by josue-suarez-wt** [comment]
Thanks for confirming! Seems that my issue was because of returning an array done via .map.

In that case, returning a fragment wrapping the array works fine!


const jsxFragments = [...].map(...);
return <>{jsxFragments}</>;
