### ISSUE TITLE
Index.d.ts does not match with Index.js

### ISSUE THREAD

**Issue by heldergoncalves92** [remarkablemark/html-react-parser#143]
Is this a bug report?
> Yes

## Expected Behavior
Default import in es modules should have a function defined.

## Actual Behavior
Default import is `undefined`.

**Comment by remarkablemark** [comment]
Published [0.10.2](https://github.com/remarkablemark/html-react-parser/tree/v0.10.2):

```sh
# npm
npm i -S html-react-parser@0.10.2

# yarn
yarn add html-react-parser@0.10.2
```
