### ISSUE TITLE
dom-to-react.d.ts should reference JSX.Element instead of React.ReactElement

### ISSUE THREAD

**Issue by yunyu** [remarkablemark/html-react-parser#145]
Although this library can be used with Preact/Inferno/etc, the typings make it hard to do so as they rely explicitly on React types. Instead, JSX.Element should be used as it's more compatible across libraries.

I'd PR this, but I'm uncertain as to how dependent the library is on React internals.

**Comment by remarkablemark** [comment]
Published [0.10.3](https://github.com/remarkablemark/html-react-parser/tree/v0.10.3):

[npm](https://www.npmjs.com/package/html-react-parser):

```sh
npm i -S html-react-parser@0.10.3
```

[yarn](https://yarnpkg.com/package/html-react-parser):

```
yarn add html-react-parser@0.10.3
```
