### ISSUE TITLE
Allow React 19 as a peer dependency

### ISSUE THREAD

**Issue by atomrevival** [remarkablemark/html-react-parser#1455]
## Problem

We're currently using this on a React 19 (RC) project and getting some peer dependencies. Seems that this works all right to just use the parser in a React 19 project, but haven't tested it conclusively.

## Suggested Solution

```json
{
  "peerDependencies": {
    "@types/react": "17 || 18",
    "react": "0.14 || 15 || 16 || 17 || 18 || 19"
  },
}
```

## Keywords

React 19, upgrade, RC

**Comment by remarkablemark** [comment]
@atomrevival thanks for opening this issue, I don't believe React 19 has been officially released yet (see [NPM](https://www.npmjs.com/package/react?activeTab=versions)). In the meantime, could you try the following? https://github.com/remarkablemark/html-react-parser/issues/1436#issuecomment-2131695591

**Comment by thany** [comment]
It's probably a good idea to stay ahead of issues like "please support React 19" when it does get released. Also, React 19 has RC status, which is especially the right moment for dependant packages to start adding support for it, in an effort to release an update on the same day as React does.

**Comment by remarkablemark** [comment]
@thany thanks for the comment. The reason why I'm not locking the RC version for React 19 is because it's still [not stable](https://x.com/sophiebits/status/1801663976973209620).

If you need to use RC 19 in your project, feel free to follow https://github.com/remarkablemark/html-react-parser/issues/1436#issuecomment-2131695591.

**Comment by ptmkenny** [comment]
[React 19 has been released](https://react.dev/blog/2024/12/05/react-19), so it would be great to add this now.  I've been using rc1 for the past few weeks with html-react-parser in my app and have experienced no problems.

**Comment by remarkablemark** [comment]
@ptmkenny thanks for the update, I'll add React 19 later today

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1628#issuecomment-2521861131
