### ISSUE TITLE
Wrong conversion with &nbsp;

### ISSUE THREAD

**Issue by ricaragao** [remarkablemark/html-react-parser#147]
When I try parse some string with `&nbsp;` it show a wrong character: `

- Version: 0.9.1
- Platform: all
- Browser: all

**Comment by remarkablemark** [comment]
Can you provide a reproducible example using [Repl.it](https://repl.it/@remarkablemark/html-react-parser) or [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/)?

**Comment by remarkablemark** [comment]
Closing issue as I'm unable to reproduce this:

- [Node.js](https://repl.it/@remarkablemark/html-react-parser-147-1)
- [Web](https://repl.it/@remarkablemark/html-react-parser-147-2)

**Comment by ricaragao** [comment]
@remarkablemark , sorry for late feedback. The problem was with font file and not with html-react-parser.
