### ISSUE TITLE
QUESTION: Any way to make this component work?

### ISSUE THREAD

**Issue by zambo** [remarkablemark/html-react-parser#149]
Hi,

Not sure if it's a bug, so I'll fill it as a question.

I'm replacing most of my static content with components without any issue, but when I try to replace a `div` with the [react-id-swiper](https://www.npmjs.com/package/react-id-swiper) component, all the inner content vanishes.

So, my question... Is it a bug or is there's a specific way to pass the children prop for this kind of component?

I'm using Gatsby with gatsby-source-graphql it that makes any difference.

Options:
```javascript
const options = {
  replace: ({ attribs, children }) => {
    if (!attribs) return

    if (attribs.class === "custom-swiper-wrapper") {
      return <Swiper {...params}>{domToReact(children, options)}</Swiper>
    }
  },
}
```

To be parsed:
```html
<div class="custom-swiper-container">
  <div class="custom-swiper-wrapper">
    <div class="swiper-slide">...</div>
    <div class="swiper-slide">...</div>
    <div class="swiper-slide">...</div>
    <div class="swiper-slide">...</div>
    <div class="swiper-slide">...</div>
    <div class="swiper-slide">...</div>
  </div>
</div>
```

Output:
```html
<div class="custom-swiper-container"></div>
```

**Comment by remarkablemark** [comment]
What you have looks correct. Can you log what `children` is here?

**Comment by zambo** [comment]
Here it is.
![image](https://user-images.githubusercontent.com/497886/79088805-2913b300-7d1a-11ea-8595-ab7ab944ef56.png)

I don't think the problem is within the children. If a replace the `Swiper` component with anything else like simple `div` or a different component, it works like a charm.

I'm using the html-react-parser to replace a bunch of Wordpress/Guttenberg blocks by custom components without any issue, except for this one.

Anyway, I've managed to achieve what I wanted trough a different method.

**Comment by remarkablemark** [comment]
Gotcha then it's most likely due to the `<Swiper>` components or the `params` passed to it.

If this is no longer an issue, can we close this issue?

**Comment by zambo** [comment]
Sure!

Thank you anyway. I was just wondering if there was any catch passing a children prop to a component.

Thanks again.

**Comment by remarkablemark** [comment]
No problem, feel free to reopen or create a new issue if you have another question.
