### ISSUE TITLE
traverse option

### ISSUE THREAD

**Issue by ggmartins** [remarkablemark/html-react-parser#153]
I'm new to react. I just want to traverse through nodes to extract some values from a HTML page (and do not replace). Would it make sense to have this option available (maybe a PR), or maybe using something else on top of html-react-parser like react-traverse. Sorry if this looks like a SO question. Thanks.

**Comment by remarkablemark** [comment]
You may not need this `html-react-parser` if you're traversing a string of HTML. Can [html-dom-parser](https://github.com/remarkablemark/html-dom-parser/) do the job for you?

**Comment by ggmartins** [comment]
it sounds like I need to traverse the json resulting from html-dom-parser somehow, maybe using .filter()? anyways, I decided to use react-traverse instead,  it was really straight forward but I'm still using react-parse regardless. Maybe In the future, I might 2 libs for a single one to get all the job done. Thanks, G.
