### ISSUE TITLE
Can i parse script and style tags using this package?

### ISSUE THREAD

**Issue by KashafS98** [remarkablemark/html-react-parser#154]
So i have a requirement, where in i want users to create small snippets of code using basic HTM/CSS/JS and i want to add those into my react app.
Will this package help me with such a need?

**Comment by remarkablemark** [comment]
So style tags are parsed and rendered but script tags are not rendered on the DOM. See [FAQ](https://github.com/remarkablemark/html-react-parser#faq) for more details.

**Comment by rgvillanueva28** [comment]
The fiddle example for parsing script seems to be not working. I am also trying to find out if this package can parse script.

**Comment by remarkablemark** [comment]
Can you link me to the broken fiddle so I can fix it?

**Comment by KashafS98** [comment]
Thank you for the help. I eventually took another route out of the problem.
