### ISSUE TITLE
lowerCaseAttributeNames: false, doesn't do his job. attributes are still lower case chars only.

### ISSUE THREAD

**Issue by jerome-diver** [remarkablemark/html-react-parser#168]
## Expected Behavior

textarea attribute name: "defaultValue" should stay upper case, but instead, become lower case chars: "defaultvalue".
i do use htmlparser2 option key to define related options to get this to work, but it still failed.

## Actual Behavior

defaultValue become defaultvalue (lower case char "v") even with htmlparser2 options setup (see below).

## Steps to Reproduce

use a html template with node elements with attributes name contain upper case chars, parse them, use htmlparse2 option to try to remove lowerCaseAttributeNames, and look at the result... still lower case attribute names.

## Reproducible Demo
```pug
textarea(type='text' id='message' name='message'
                        rows="4" cols="50" defaultValue="")
```
(pug template fetched to a react client, then console.log show the template rendered text has still upper case chars attribute names)
```javascript
parse(this.state.content, 
            { htmlparser2: {
                xmlMode: true,
                lowerCaseAttributeNames: false,
                lowerCaseTags: false
              } 
            } )
```

## Environment

- Version:
0.13.0
- Platform:
archlinux
- Browser:
firefox-78.0.2

**Comment by remarkablemark** [comment]
Thanks for opening this issue @jerome-diver. Can you help me reproduce this issue on [Repl.it](https://repl.it/@remarkablemark/html-react-parser), [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/), or [CodeSandbox](https://codesandbox.io/s/940pov1l4w)?

**Comment by jerome-diver** [comment]
No i can not. But you have all the elements requested to reproduce the problem. Just parse a html string contained upper case attributes name and you will see.

**Comment by lazerwalker** [comment]
@remarkablemark I'm experiencing this too — here's a fairly trivial test case: https://repl.it/repls/FriendlyYearlyPublisher#index.js

**Comment by remarkablemark** [comment]
@lazerwalker What version of `html-react-parser` are you using? I see in your Repl.it that you're using [0.10.1](https://repl.it/repls/FriendlyYearlyPublisher#package-lock.json).

This feature was made available in [0.12.0](https://github.com/remarkablemark/html-react-parser/issues/62#issuecomment-639914562). Also, this only works server-side (Node.js) and does not work client-side (browser).

**Comment by lazerwalker** [comment]
aha, sorry about that — I just clicked the Repl.it link you posted above and used whatever it gave me. But it'll be failing for me locally since I'm doing it in the browser.

The README doesn't specify that this feature doesn't work in the browser. I'm happy to submit a PR to update it, but just wanted to confirm: is it specifically this flag that isn't supported, or changing any htmlparser2 settings?

**Comment by remarkablemark** [comment]
@lazerwalker Yes a PR to explicitly state that this feature is available in >=`0.12.1` and only works on the server (Node.js) and not the client (browser) would be greatly appreciated.

**Comment by danielsnider** [comment]
This is an issue for me too. Anyone have a work-around?

**Comment by lazerwalker** [comment]
I personally did not manage to find a browser (rather than Node) solution, but I have not looked at this in a year.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I'm also looking for a solution for this problem, our app is running in the browser...? Actually this issue should be reopened @remarkablemark ?
