### ISSUE TITLE
Export cssToJs

### ISSUE THREAD

**Issue by christianfredh** [remarkablemark/html-react-parser#177]
I'm trying to find a library to convert inline css string to React css style object. Example:

"background-color: blue; margin-top: 10px"

to:

{
	backgroundColor: 'blue',
	marginTop: '10px'
}

I understand that this is what cssToJs function does. And since I anyway use this library , it would be great if this function could be exported. I guess in a separate module, like attributesToProps, would be best.

**Comment by jordie23** [comment]
Agreed. I basically copied it out of these repo to use and I'm not happy about doing it that way. Would be great if it was just exported.

**Comment by remarkablemark** [comment]
I moved [`cssToJs`](https://github.com/remarkablemark/html-react-parser/blob/4b5fad9ca5ea47d360a1b894ed0f675f879d7f65/lib/attributes-to-props.js#L76) to another package [`style-to-js`](https://github.com/remarkablemark/style-to-js) in #182

So in [v0.14.2](https://github.com/remarkablemark/html-react-parser/releases/tag/v0.14.2):

```sh
# npm
npm i html-react-parser@0.14.2

# yarn
yarn add html-react-parser@0.14.2
```

It will install the dependency [`style-to-js`](https://www.npmjs.com/package/style-to-js) so you can do the following:

```js
const styleToJS = require('style-to-js').default;

styleToJS('background-color: #BADA55', { reactCompat: true });
```

Let me know if this helps. You can check out the `style-to-js` [README](https://github.com/remarkablemark/style-to-js#readme) for more details.

**Comment by jordie23** [comment]
That’s awesome. Thanks!

**Comment by remarkablemark** [comment]
@christianfredh Let me know if there's anything else that you need. Otherwise, can you please close this issue?

**Comment by christianfredh** [comment]
I've tested it now and it works great, thank you!

I still need this helper function to check for null/undefined at the moment:

```
function cssToJs(style: string | undefined | null) {
  return styleToJS(style ?? '', { reactCompat: true })
}
```

I see there is a check for this in the actual code which returns an empty object. Maybe that could be reflected typescript-wise as well, I don't know. Either way, it works great, and I will close the issue.
