### ISSUE TITLE
Add class name to html before parsing

### ISSUE THREAD

**Issue by RDjarbeng** [remarkablemark/html-react-parser#180]
Is there a way to add class names in react to the html elements to be parsed?

Supposing I have code similar to the ordered list below
```
<ol className="pt-0 mb-1">
 <li>List content ... </li>
</ol>
```

and I now want to replace it with almost the same code but sourced from markdown files.
Assume it's stored in a variable

```
 text ="
<ol>
 <li>List content ... </li>
</ol>"
```

_Notice the className attribute is missing in the second block of code._
So my question is does html-react-parser support adding class names as an option to the top level container <ol> so it is like the first code above?

for example parse(text, {classattribute: "pt-0"})

**Comment by remarkablemark** [comment]
Have you tried using the [replace](https://github.com/remarkablemark/html-react-parser#replacedomnode) option?

**Comment by RDjarbeng** [comment]
Thanks it worked perfectly
