### ISSUE TITLE
TypeError: Text is not a constructor

### ISSUE THREAD

**Issue by Azumi0** [remarkablemark/html-react-parser#198]
## Expected Behavior

React component render

## Actual Behavior

Crash of entire react application. On calling `parse` the console shows the following error:
`TypeError: Text is not a constructor
    at formatDOM (utilities.js:93)
    at HTMLDOMParser (html-to-dom-client.js:38)
    at HTMLReactParser (index.js:27)`
The same code worked fine on version 0.10.3 but after updating to 1.0.0 I can't even render the page.

## Steps to Reproduce

I tried calling `parse` with a simple test string
`parse('<p>trara</p>')`
And it showed the following error in the console:
`Uncaught TypeError: Element is not a constructor
    at formatDOM (utilities.js:85)
    at HTMLDOMParser (html-to-dom-client.js:38)
    at HTMLReactParser (index.js:27)`

I have a feeling that I am missing some peer dependency but I can't find which one exactly. 

## Environment

- Version: 1.0.0
- Platform: Linux
- Browser: Chrome v85.0
- Builder: Webpack with typescript

**Comment by remarkablemark** [comment]
@Azumi0 can you try deleting your lockfile and `node_modules` and reinstalling?

```sh
rm package-lock.json # yarn.lock
rm -rf node_modules
npm i
```

The latest version (1.0.0) is working on:

- [CodeSandbox](https://codesandbox.io/s/940pov1l4w)
- [Repl.it](https://repl.it/@remarkablemark/html-react-parser)
- [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/)

**Comment by Azumi0** [comment]
Hi, I tried removing the `node_modules` but not the `package-lock.json`. Removing the lock file helped, Now I just need to test my whole application to see if anything exploded after updating a lot of packages (thanks to deleting the lockfile) :smile: 

Thanks for the assistance :+1:
