### ISSUE TITLE
TS error: domToReact(node.children) not working in v1.0.0+

### ISSUE THREAD

**Issue by allanmc** [remarkablemark/html-react-parser#207]
## Expected Behavior

Replace using `domToReact(node.children)` as shown in README should work in Typescript.

## Actual Behavior

```
Argument of type 'Node[]' is not assignable to parameter of type 'DOMNode[]'.
  Type 'Node' is not assignable to type 'DOMNode'.
    Type 'Node' is missing the following properties from type 'Text': data, nodeValuets(2345)
```

## Reproducible Demo

https://codesandbox.io/s/little-dew-h4l9h?file=/src/App.tsx

## Environment

- Version: 1.0.0+

**Comment by remarkablemark** [comment]
Thanks for opening the issue @allanmc

I can confirm the TS error. The fix would be to include domhandler `Node` in `DOMNode` type (see [line](https://github.com/remarkablemark/html-react-parser/blob/v1.1.1/index.d.ts#L19)). I will open a PR shortly.

**Comment by remarkablemark** [comment]
@allanmc please review PR #208

**Comment by remarkablemark** [comment]
Published [v1.1.2](https://github.com/remarkablemark/html-react-parser/releases/tag/v1.1.2):

[npm](https://www.npmjs.com/package/html-react-parser):

```sh
npm i html-react-parser@1.1.2
```

[Yarn](https://yarnpkg.com/package/html-react-parser):

```sh
yarn add html-react-parser@1.1.2
```

**Comment by csurfleet** [comment]
Hi, I think I must be doing something wrong. I've used create-react-app to spin up a typescript app and added html-reace-parser. I'm trying to use domToReact but its complaining about the children property:
`const options: HTMLReactParserOptions = {
        replace: (domNode: DOMNode) => {
          if (domNode instanceof Element) {
            if (domNode.tagName === 'A') {
                return <span>{domToReact(domNode.children, options)}</span>
            }
          }
        }
      };

    return (<div>
        {parse(html, options)}
    </div>);`

I'm getting the error "Argument of type 'HTMLCollection | (ChildNode[] & HTMLCollection)' is not assignable to parameter of type 'DOMNode[]'."

**Comment by remarkablemark** [comment]
@csurfleet can you provide a reproducible example in [CodeSandbox](https://codesandbox.io/s/html-react-parser-z0kp6)? Also, if you think this is a bug, please open a new issue.
