### ISSUE TITLE
es6 code sneak in / breaks ie11

### ISSUE THREAD

**Issue by lhtdesignde** [remarkablemark/html-react-parser#213]
## Expected Behavior

There should be es5 code only is dist build.

## Actual Behavior

When building the latest version 1.2.1 with webpack for production, it adds es6 code into the dist build.
I'm not 100% sure why that is, as I couldn't find the "const" dist build itself.
For me this new addition gets also compiled:
https://github.com/remarkablemark/html-react-parser/commit/4caa88cc3d6eaf9c28acaf6a344a8d7353a1c58b#diff-d6299b5bb2afc0956126a0adb12fd89829e01a4cc025e7277a092228b96f32e4R4

If any helpful, this is how it looks when compiled:
<img width="901" alt="Screen Shot 2021-01-21 at 13 58 10" src="https://user-images.githubusercontent.com/5528640/105354452-de03c600-5bf0-11eb-96cd-7bcbc8f5cc15.png">

When I downgrade to version 1.2.0, that is fine and IE11 works. Is there a chance to make this es5 code?

## Environment

- Version: 1.2.1
- Platform: mac os big sur, webpack 5
- Browser: IE11

**Comment by remarkablemark** [comment]
Thanks for opening this issue @lhtdesignde

This is happening because [webpack](https://webpack.js.org/) prioritizes `module` over `main` from `package.json`:

So instead of:

```js
// webpack.config.js
module.exports = {
  //...
  resolve: {
    mainFields: ['browser', 'module', 'main'],
  },
};
```

See if you can do:

```js
// webpack.config.js
module.exports = {
  //...
  resolve: {
    mainFields: ['browser', 'main', 'module'],
  },
};
```

See [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields)

**Comment by remarkablemark** [comment]
Also, what version of webpack are you using?

**Comment by lhtdesignde** [comment]
webpack 5.16.0

**Comment by lhtdesignde** [comment]
SO good! Thanks for this answer @remarkablemark. That made it work!

**Comment by remarkablemark** [comment]
Great to hear! Can this issue be closed @lhtdesignde?

**Comment by lhtdesignde** [comment]
yes thanks!

**Comment by remarkablemark** [comment]
Just a heads up @lhtdesignde, I published [v1.2.2](https://github.com/remarkablemark/html-react-parser/releases/tag/v1.2.2), which removes `const` from `index.mjs`.

This should fix the root cause of your issue (you can undo your `webpack.config.js` changes).

**Comment by lhtdesignde** [comment]
thank you very much!

**Comment by remarkablemark** [comment]
You're welcome! Let me know if you encounter any issues.
