### ISSUE TITLE
<br<p> causes "Script error."

### ISSUE THREAD

**Issue by jimthebob** [remarkablemark/html-react-parser#236]
Bug Report
## Expected Behavior
      `<br</p>
    ` is  incorrect html. It should be `<br><p>` However, it does cause an error and doesn't display anything. This can be replicate in the jsfiddle item provided on the github web page i.e. https://jsfiddle.net/remarkablemark/7v86d800/

The text is displayed without causing a blank screen
## Actual Behavior
blank screen and script error

## Steps to Reproduce
This can be replicated in the jsfiddle item provided on the github web page i.e. https://jsfiddle.net/remarkablemark/7v86d800/

## Reproducible Demo
See 
* JSFiddle: https://jsfiddle.net/remarkablemark/7v86d800/
and change one line to     **const html = `
      <p>
        This is a demo of <span id="replace">placeholder</span>
      <br</p>
    `;**

## Environment
All environments - see jsfiddle demo
- Version:
- Platform:
- Browser:

**Comment by remarkablemark** [comment]
Thanks for opening the issue @jimthebob. This error seems to be expected behavior since invalid HTML markup will cause the parser to throw. I recommend sanitizing your HTML before running it through the parser.

**Comment by jimthebob** [comment]
Ok, thanks for your reply. I had wrongly assumed that the parse would handle the incorrect html.
