### ISSUE TITLE
Dom Handler options

### ISSUE THREAD

**Issue by afk-mario** [remarkablemark/html-react-parser#239]
I need the startIndex and endIndex from the Dom handler in my react components, currently it seems the properties are always null, would like to pass in the options object, options to the DomHandler lib similar to how it's currently done for `htmlparser2`

**Comment by remarkablemark** [comment]
@afk-mario Are you able to use [htmlparser2 options](https://github.com/remarkablemark/html-react-parser/tree/v1.2.5#htmlparser2)?

Note that this only works on the server-side and not on the client-side.

**Comment by afk-mario** [comment]
Hmm you are right! totally missed that, I'm using it on the browser so this probably is out of scope, feel free to close this issue

**Comment by remarkablemark** [comment]
Thanks @afk-mario, closing issue.

**Comment by Dachong233** [comment]
> @afk-mario Are you able to use [htmlparser2 options](https://github.com/remarkablemark/html-react-parser/tree/v1.2.5#htmlparser2)?
> 
> Note that this only works on the server-side and not on the client-side.

I faced the same problem, but I had some questions. It seems like that `domhandler` support `withStartIndices` and `withEndIndices` on the client-side, I can use it to parse a html string and access node's index.But why not work for `html-react-parser`.

Thank you very much for your response!

**Comment by Dachong233** [comment]
> > @afk-mario Are you able to use [htmlparser2 options](https://github.com/remarkablemark/html-react-parser/tree/v1.2.5#htmlparser2)?
> > Note that this only works on the server-side and not on the client-side.
> 
> I faced the same problem, but I had some questions. It seems like that `domhandler` support `withStartIndices` and `withEndIndices` on the client-side, I can use it to parse a html string and access node's index.But why not work for `html-react-parser`.
> 
> Thank you very much for your response!

Oh, I had found the [issue#30](https://github.com/remarkablemark/html-dom-parser/issues/30) in lib `html-dom-parser`. But I wonder if there is an easier way to choose between server and client？

**Comment by remarkablemark** [comment]
If you're using webpack, you could do something like https://github.com/remarkablemark/html-react-parser/issues/736#issuecomment-1612365781

**Comment by Dachong233** [comment]
> @Dachong233 If you're using webpack, you could do something like [#736 (comment)](https://github.com/remarkablemark/html-react-parser/issues/736#issuecomment-1612365781)

Thanks for your quick reply :) I'll try it later today.

**Comment by remarkablemark** [comment]
@Dachong233 thanks and feel free to create a new issue/discussion if you have further questions.
