### ISSUE TITLE
Wrong return types on attributesToProps

### ISSUE THREAD

**Issue by EoleO** [remarkablemark/html-react-parser#242]
### Description
In the file `attributes-to-props.d.ts` the return types of `attributesToProps` function is a `Object` with `String` items.

https://github.com/remarkablemark/html-react-parser/blob/80bbea06fac6825f2667060f979fbd54b407e748/lib/attributes-to-props.d.ts#L3-L4

But in the `attributesToProps` function, `setStyleProp` is call to transform `CSSInline` to `StyleObject`.

https://github.com/remarkablemark/html-react-parser/blob/80bbea06fac6825f2667060f979fbd54b407e748/lib/attributes-to-props.js#L62

The return of the function is an `StyleObject` and not a `String`.

https://github.com/remarkablemark/html-react-parser/blob/80bbea06fac6825f2667060f979fbd54b407e748/lib/utilities.js#L76-L87

The result of this miss-typing is an error if you would like to get an `CSSProperty`.

<img width="452" alt="Capture d’écran 2021-04-16 à 10 42 51" src="https://user-images.githubusercontent.com/10879770/114997956-ba26e800-9ea0-11eb-8b0a-081d69d0cea5.png">

### Expected Behavior

Update `attributes-to-props.d.ts` with :

```ts
export type Attributes = Record<string, string>; 
export type Props = Record<string, string> & {
  style: Record<string, string>;
}; 
```

**Comment by remarkablemark** [comment]
Thanks for creating this issue @EoleO. Would you like to open a PR?

**Comment by remarkablemark** [comment]
@EoleO please review #245

**Comment by remarkablemark** [comment]
Published [v1.2.6](https://github.com/remarkablemark/html-react-parser/releases/tag/v1.2.6):

[npm](https://www.npmjs.com/package/html-react-parser):

```sh
npm i html-react-parser@1.2.6
```

[Yarn](https://yarnpkg.com/package/html-react-parser):

```sh
yarn add html-react-parser@1.2.6
```

**Comment by EoleO** [comment]
Thank you for your responsiveness

**Comment by remarkablemark** [comment]
@EoleO Of course, feel free to reopen if you are still experiencing an issue.
