### ISSUE TITLE
TypeScript: export types of 'domhandler/lib/node'

### ISSUE THREAD

**Issue by natterstefan** [remarkablemark/html-react-parser#252]
Hi @remarkablemark,

I think it's best to create an issue for our discussion (starting [here](https://github.com/remarkablemark/html-react-parser/pull/201#issuecomment-825549767)) in the merged PR than to discuss further there.

As [suggested](https://github.com/remarkablemark/html-react-parser/pull/201#issuecomment-833261077) the solution could be to export the types alongside `html-react-parser`'s types instead of having people installing the package only to use the types.

What do you think?

**Comment by remarkablemark** [comment]
@natterstefan the library is already exporting types in [index.d.ts](https://github.com/remarkablemark/html-react-parser/blob/v1.2.6/index.d.ts). What type are you suggesting that needs to be exported?

**Comment by natterstefan** [comment]
Hi @remarkablemark,

I think I see my confusion now. When I first had the issue in Next.js and with TypeScript, I saw [this comment](https://github.com/remarkablemark/html-react-parser/issues/221#issuecomment-771600574). The comment connotes that you have to `import { Element } from "domhandler/lib/node";` to use the `Element` type. But in fact (and I was not aware of that until now), you export it already [here](https://github.com/remarkablemark/html-react-parser/blob/48a46de8377f811d969a34ff49bc5fcd7c7cd197/index.d.ts#L19).

It would probably help to tell people in the README, that for type checking only you do not need to install `domhandler`, but use the built-in types: https://github.com/remarkablemark/html-react-parser#replace-with-typescript.

It will not help though when people want to check the instance of the element.

Then we are back at the problem that one needs to install another library to do that. 🤔

**Comment by remarkablemark** [comment]
Since [v1.2.6](https://github.com/remarkablemark/html-react-parser/blob/v1.2.6/package.json#L40), `domhandler` comes installed as a dependency.

Do we want any additional code or `README.md` improvements?

**Comment by natterstefan** [comment]
Hi @remarkablemark,

> Since [v1.2.6](https://github.com/remarkablemark/html-react-parser/blob/v1.2.6/package.json?rgh-link-date=2021-06-10T15%3A52%3A01Z#L40), `domhandler` comes installed as a dependency.
> 
> Do we want any additional code or `README.md` improvements?

To be honest I am not sure. My problem was solved by installing the `domhandler` package. Only then I was able to check the instance of the element.

> It will not help though when people want to check the instance of the element.

This is the actual problem that is left, when we put the types aside (v1.2.6 handles that already). Wouldn't it be possible to export the runtime `Element` (as described [here](https://github.com/remarkablemark/html-react-parser#replace-with-typescript)) as well? 

Tree shaking should take care of keeping the bundle size small if not used, doesn't it?

**Comment by peckyboy** [comment]
Some of the properties in the HTMLReactParserOptions type are missing (eg children,attribs).

**Comment by remarkablemark** [comment]
That's fair, I'm open to exporting `Element`. Would you be interested in opening a PR?

**Comment by natterstefan** [comment]
Hi @remarkablemark,

I finally had time to contribute and I've created a PR for you to review here https://github.com/remarkablemark/html-react-parser/pull/296.

**Comment by remarkablemark** [comment]
Thanks for the contribution @natterstefan, your changes will be released in [1.4.0](https://github.com/remarkablemark/html-react-parser/pull/306)

**Comment by natterstefan** [comment]
Thank you very much and you're welcome, @remarkablemark!
