### ISSUE TITLE
Throws error when styles are corrupted

### ISSUE THREAD

**Issue by dogriffiths** [remarkablemark/html-react-parser#256]
## Expected Behavior

- Parse a string with a corrupted style attribute, e.g. ‘&lt;p style="font - size: 1em"&gt;X&lt;/p&gt;’
- Return a version that skips the corrupted style ‘&lt;p&gt;X&lt;/p&gt;’? 

## Steps to Reproduce

Throws an exception: undefined:1:6: property missing ':'
## Reproducible Demo
https://jsfiddle.net/bjwmd5s6/

## Environment

- Version: 1.2.6
- Platform: Mac
- Browser: Tested on Firefox

**Comment by remarkablemark** [comment]
Published [v1.2.8](https://github.com/remarkablemark/html-react-parser/releases/tag/v1.2.8):

[npm](https://www.npmjs.com/package/html-react-parser):

```sh
npm i html-react-parser@1.2.8
```

[Yarn](https://yarnpkg.com/package/html-react-parser):

```sh
yarn add html-react-parser@1.2.8
```
