### ISSUE TITLE
How should/can we use css selectors to traverse the nodes?

### ISSUE THREAD

**Issue by iDVB** [remarkablemark/html-react-parser#268]
Currently we want to supply a `replace` function that can detect a given pattern and then traverse that node's children to handle that node in two ways:

1) Find what the value is of a specific `attribs` by traversing its children and use that value to define which react component should wrap the root node.
2) Remove ALL child nodes to that node other than `Text`.

Diving into the dependencies I can see both [cheerio and css-select](https://github.com/fb55/htmlparser2#ecosystem) are used. Not sure if its even possible to use one of those here?

**Comment by remarkablemark** [comment]
Thanks for opening the issue @iDVB! Unfortunately, we don't have an API to support parsing like `cheerio` or `css-select`. I recommend checking out the additional [replace](https://github.com/remarkablemark/html-react-parser/tree/v1.4.2#replace) examples to see if they're applicable. Feel free to reopen the issue if you still have any questions.
