### ISSUE TITLE
unable to rightly parse html when it contain some html tags with no ends.

### ISSUE THREAD

**Issue by AlenToma** [remarkablemark/html-react-parser#282]
I am unable to parse the current html from some reason

```html
<div>
<div id="chr-content">
<span>
  lkjasdkjasdkljakldj
</div>
</div>
`
```

## My current Code is

```js
  const validate =()=> {
       var h = html.replace(/<!DOCTYPE html>/g, "").
          replace(/[[class]]/g, "").
          replace(/[[id]]/g, "")
    var container = parse("<div>" + h + "</div>");
       var content = container.querySelector("#chr-content");
        setFound(content != null ? "found" : "not found")
  }
```

This is on Node.js with the latest version 4.1.4

Here is snack example if you would like to test

[snack](https://snack.expo.dev/@alentoma/html-test)

**Comment by remarkablemark** [comment]
Apologies for the late response @AlenToma but are you still unable to parse the HTML?

**Comment by AlenToma** [comment]
I am using it together with `react-native-html-parser`

`react-native-html-parser` will enclose all open html tags and then I parse the html again.
