### ISSUE TITLE
The image will be download even without render it to the page  when parsing images

### ISSUE THREAD

**Issue by iEricKoh** [remarkablemark/html-react-parser#39]
Currently I am try to parse the html that contains ``img`` tag.

My template text: 
````
    <div>
      <img src="imgUrl" alt="" />
    </div>
````

After parsed this template, the image will be download even without insert the parse result.

Because I am going to wrap all the images into a lazy load component, which works with your component.

The following could help to parse string to document, even the string contains image tag, the image won't be downloaded.

````
    const parser = new domparser();
    const doc = parser.parsefromstring(text, "text/html")
````

**Comment by remarkablemark** [comment]
@iEricKoh Thanks for bringing this to my attention.

Currently, the package depends on [html-dom-parser](https://github.com/remarkablemark/html-dom-parser) which uses [DOMParser for client parsing](https://github.com/remarkablemark/html-dom-parser/blob/v0.0.2/lib/html-to-dom-client.js#L63). However, there's an error in the if logic which is causing it to be skipped for the fallback approach.

I opened an issue: remarkablemark/html-dom-parser#1

**Comment by remarkablemark** [comment]
The issue should be resolved in the latest version:
```sh
$ npm install html-react-parser@0.3.4
```
