### ISSUE TITLE
Module not found: Error: Can't resolve 'react-dom/lib/HTMLDOMPropertyConfig'

### ISSUE THREAD

**Issue by vuldin** [remarkablemark/html-react-parser#42]
It looks like the current version of this project is attempting to use a private React API that has been removed in recent versions of React. I'm getting the following error when trying to use this library within [zeit](https://zeit.co/) [next](https://github.com/zeit/next.js) project while building for production(`npm run build`):
```bash
{ Error: ./node_modules/html-react-parser/lib/property-config.js
Module not found: Error: Can't resolve 'react-dom/lib/HTMLDOMPropertyConfig' in '<node_modules path>/html-react-parser/lib'
resolve 'react-dom/lib/HTMLDOMPropertyConfig' in '<node_modules path>/html-react-parser/lib'
  Parsed request is a module
  using description file: <node_modules path>/html-react-parser/package.json (relative path: ./lib)
```
[Here](https://twitter.com/dan_abramov/status/798926305030877184) is a tweet from Dan Abramov related to the issue.

**Comment by remarkablemark** [comment]
@vuldin Are you sure you have the correct version of `html-react-parser`, `react`, and `react-dom` installed? I tried to reproduce the issue but everything still worked for me.

I updated `react` and `react-dom` based on [`next`'s specified versions](https://github.com/zeit/next.js/blob/v3-beta/package.json#L135-L136):
```sh
$ npm ls react react-dom
html-react-parser@0.3.5
├── react@15.5.4
└── react-dom@15.5.4
```

Then I ran `npm test` and it passed with no errors.

Some more information:
```sh
$ npm version
{ 'html-react-parser': '0.3.5',
  npm: '5.0.3',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.1.3',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }
```

What versions of `html-react-parser`, `react`, and `react-dom` are you using?

**Comment by remarkablemark** [comment]
@vuldin Were you able to confirm the versions? If there are no more questions, then I'll assume that the issue has been resolved.

**Comment by vuldin** [comment]
I apologize for no response yet, but I will get back with more details by this time tomorrow (or sooner). I need to reinstall the module... I uninstalled after this issue showed up so I could make progress on my project.

**Comment by vuldin** [comment]
I just created a new project, installed `react`, `react-dom`, `next`, and `html-react-parser`. N problems appeared, so it looks like this issue is related to some dependency issue in my initial project. Sorry about the incorrect issue! Thanks.

**Comment by remarkablemark** [comment]
No problem. Glad that everything worked out!
