### ISSUE TITLE
TypeError: htmlToDOM is not a function

### ISSUE THREAD

**Issue by muhmushtaha** [remarkablemark/html-react-parser#445]
## Expected Behavior

 import parser from 'html-react-parser';
Use the parser normally and render the html 

## Actual Behavior

Cause a type error
![image](https://user-images.githubusercontent.com/25417060/152686436-614c9c28-72d7-432b-8767-2a2d5579d5cd.png)

## Steps to Reproduce

1- Install the latest version of package 1.4.7
2- Use it normally like this
import parse from 'html-react-parser';
parse('<p>Hello, World!</p>');

## Environment

- Version: html-react-parser@1.4.7, react-dom@17.0.2, next@10.0.7
- Platform: ReactJS, NextJS
- Browser: Google Chrome

**Comment by remarkablemark** [comment]
@muhmushtaha can you confirm that version 1.4.6 still works as expected? If so, I will revert the changes in 1.4.7

**Comment by muhmushtaha** [comment]
Yes, I reverted the version to 1.4.6 and tested it, it works without issues. 
@remarkablemark

**Comment by remarkablemark** [comment]
Thanks, I'll open a PR for the fix for next@10.

In my investigation, I discovered that there is no error if you're on next@11 or next@12.

**Comment by remarkablemark** [comment]
Released `1.4.8`. See https://github.com/remarkablemark/html-react-parser/pull/447#issuecomment-1030909291
