### ISSUE TITLE
Detect last child

### ISSUE THREAD

**Issue by aress31** [remarkablemark/html-react-parser#465]
Is there an easy way to detect if a tag is the last child, for instance, I replace all my `p` with the `Typography` component as follows:

```js
const parseHeroOptions = {
  replace: (domNode) => {
    if (domNode.attribs && domNode.name === 'p')
      return (
        <Typography
          align='justify'
          color='text.secondary'
          sx={{ fontWeight: 'bold' }}
          variant='h6'
        >
          {domToReact(domNode.children, parseOptions)}
        </Typography>
      );
  },
};
```

However, I would need to know if the `p` tag is the last one to be able to set the `paragraph` prop accordingly. Or a way to include custom parameter to the `parseHeroOptions` method so that I can handle the logic outside of this method.

Any clue?

**Comment by remarkablemark** [comment]
@aress31 it's possible if you trim all whitespace for your HTML markup. Then you can:

1. Check against parent's last child or
2. Check there is no next element

# Approach 1

```js
parse('<ul><li>First</li><li>Last</li></ul>', {
  replace: (domNode) => {
    const parentTag = 'ul';
    const childTag = 'li';

    if (
      domNode.parent &&
      domNode.parent.name === parentTag &&
      domNode.name === childTag &&
      domNode.next === null
    ) {
      console.log(domNode.children[0].data);
    }
  },
});
```

# Approach 2

```js
parse('<ul><li>First</li><li>Last</li></ul>', {
  replace: (domNode) => {
    const parentTag = 'ul';
    const childTag = 'li';

    if (
      domNode.parent &&
      domNode.parent.name === parentTag &&
      domNode.name === childTag &&
      domNode === domNode.parent.children[domNode.parent.children.length - 1]
    ) {
      console.log(domNode.children[0].data);
    }
  },
});
```

# Demo

https://replit.com/@remarkablemark/html-react-parser-465

**Comment by aress31** [comment]
@remarkablemark thanks for the answer I went for an easier solution of adding a class to the last <p> of each section so that I can flag them using `domNode.attrbs.class`.

I reckon it could be worth it adding a method such as `domNode.isLastChild` that would return whether the element is the last child of a sequence of a given tag. Could even extend that to `isFirstChild` or `isChild(n)`.

What do you think?

**Comment by remarkablemark** [comment]
@aress31 Thanks for the suggestion but I believe adding this method will lead to a lot of complexity and edge cases since the HTML to DOM parsing is handled by [html-dom-parser](https://github.com/remarkablemark/html-dom-parser).

Since your original question was answered, I will close this issue.
