### ISSUE TITLE
Is it compatible with htmlparser format?

### ISSUE THREAD

**Issue by oliverodaa** [remarkablemark/html-react-parser#47]
Is it possible for us to call the following?
```
// htmlparser format, not htmlparser2
const htmlparserDoc = [ { type: 'tag'
  , name: 'a'
  , attribs: { href: 'test.html' }
  , children: [ { data: 'hello world', type: 'text' } ]
  }
];

domToReact(htmlparserDoc, options);
```

The `htmlparser2` format contains circular references, which prevents us from calling `JSON.stringify()` on it, so we'd like to use `htmlparser` if we can.

**Comment by remarkablemark** [comment]
@oliverodaa Should be possible:

```sh
$ node
> const domToReact = require('html-react-parser/lib/dom-to-react');
> const htmlparserDoc = [{ type: 'tag', name: 'a', attribs: { href: 'test.html' }, children: [{ data: 'hello world', type: 'text' }] }];
> domToReact(htmlparserDoc);
{ '$$typeof': Symbol(react.element),
  type: 'a',
  key: null,
  ref: null,
  props: { href: 'test.html', children: 'hello world' },
  _owner: null,
  _store: {} }
```

Let me know if you experience any issues; otherwise, please close the issue if it works.

**Comment by oliverodaa** [comment]
Thank you for the quick response! I am still in the process of working on it but will be sure to close the issue when I have confirmed that it either works or doesn't work.

**Comment by oliverodaa** [comment]
I can confirm that it does in fact work! I ended up using `htmlparser2` but then when I called `JSON.stringify()` I removed any circular references like this:

```js

JSON.stringify(obj,
    function(key, value) { 
        return key === 'parent' || key === 'next' || key === 'prev'
            ? undefined
            : value;
  });
```
