### ISSUE TITLE
Parsing Events / Event Listeners

### ISSUE THREAD

**Issue by KDCinfo** [remarkablemark/html-react-parser#48]
How would you handle applying event listeners? My current HTML/JavaScript app is currently complemented with `addEventListener()`s, which I figured I would just refactor to be `onclick`, `onchange`, etc. However, neither `onclick` nor `onClick` seemed to work. I also tried with `='return myFunc(e)'`, `='myFunc(e)'`, and just `='myFunc'`. I see the `className`s changing/working (when I change them), but I can't seem to get the event added.

I'm thinking I will need to use the `replace` via the `parser options` and add them in there, but figured I'd check to see if that's the proper (if not only) approach.

Also, many thanks for this utility!

**Comment by KDCinfo** [comment]
I was able to add my own `onClick` event handler via the `parser options` as referenced in your examples. I will likely end up going with a `switch` statement, but until I get there, below was my workable test code:
```
class ExpiredToBe extends React.Component {
  state = {
    expiredToBeForm: '<form><button class="input-save">Save</button></form>'
  };
  inputSaveClick = (e) => {
    e.preventDefault();
    console.log('inputSaveClick: ', e.target); // Works !!!
  }
  render() {
    const parserOptions = {
      replace: (domNode) => {

        const thisAttribs = domNode.attribs;

        if (domNode.name === 'div') {
          console.log('domNode DIV', domNode); // Reality check... :)
        }

        if (!thisAttribs) {
          return domNode;   // Text nodes and whatnot.

        } else if (thisAttribs && 
                   thisAttribs.class && 
                   thisAttribs.class.indexOf('input-save') >= 0
                  )
        {
          return (
            <button className='input-save' onClick={this.inputSaveClick}>Save</button>
          );

        } else {            // Will do other `else if`s
          return domNode;
        }
      }
    };
    return(
      <div>
        { Parser(this.state.expiredToBeForm, parserOptions) }
      </div>
    );
  }
}
```

**Comment by remarkablemark** [comment]
@KDCinfo your solution is the recommended approach for parsing event listeners in the HTML markup. Please close the issue if there are no other questions.

**Comment by KDCinfo** [comment]
Good to know. Thanks!
