### ISSUE TITLE
how to use Parse in loop for replace the value with multiple?

### ISSUE THREAD

**Issue by jitendrapal00** [remarkablemark/html-react-parser#51]
just like as 

("<a id="abc">hello</a>")

and I want to replace hello with match the tag id and found in an array and return and HTML. Is It Possible to Parser in loop?

**here is my code** 

> rowTextContent = <p>[quote]4becc77f37ba3[/quote]</p>

  

> Parser(rowTextContent, {
>                                     replace: (domNode) => {
> 
>                                         if (domNode) {
> 
>                                              var re = new RegExp("^_quote_([a-z0-9]+)_quote_$");
>                                             var quoteData = domNode.childrenreplace('[quote]', '_quote_').replace('[/quote]', '_quote_');
> 
>                                             if (re.test(quoteData)) {
> 
>                                                 var id = re.exec(quoteData)[1];
>                                                                                        
>                                                 for (let i = 0; i <= this.state.rowData.narration.text.quotes.length; i++) {
> 
>                                                     let text = this.state.rowData.narration.text.quotes[i];
>                                                                       
>                                                     if (id === text.parent) {
> 
>                                                         return (
> 
>                                                             <div className="quote" id={text.slug} key={i}>
>                                                                 <div className="heading" onClick={this.props.showHideRow.bind(this, text.slug)}>
>                                                                     <img id="bullet105" src={`${mediaUrl}/interface/triangle0`}
>                                                                         className={this.state.isShowRow && this.state.textSlug1 === text.slug ? "imgRadious" : "noimgRadious"} />
>                                                                     <span className="heading">{text.heading}</span>
>                                                                 </div>
>                                                                 {
>                                                                     <div className="textcontainer " style={{ display: 'block', overflow: 'hidden', height: 'auto' }}>
>                                                                         <div className="text" duration="5">
>                                                                             {textContent}
>                                                                         </div>
>                                                                     </div>
>                                                                 }
>                                                             </div>
>                                                         )
>                                                         
>                                                     }
>                                                 }
>                                         
>                                             }
>                                         }
>                                     }
>                                 })

any suggestion guys?

**Comment by jitendrapal00** [comment]
Hello @remarkablemark, my question was, I am using 

> content = React.createElement('span', { onMouseOver: this.onMouseOver, onClick: this.props.commentrey }, Parser(content));

and I need to replace some value then I am using  Parser(content, {

                                    replace: (domNode) => {

_here I am my code for the match and return value or replace  the value_ 

}}

when I do pass the parameter   "content" to **Parser**  then It is an error occurs **TypeError: First argument must be a string**

**Comment by jitendrapal00** [comment]
I solved my issue, it has miner mistake 

Thanks **@remarkablemark**

**Comment by remarkablemark** [comment]
No problem, great to hear that you were able to resolve your issue
