### ISSUE TITLE
Can I use onClick within the parser?

### ISSUE THREAD

**Issue by jackdh** [remarkablemark/html-react-parser#53]
Hello,

I would like to be able to use onClick={this.work}, however the onClick does not seem to work.

Is this the expected behavior?

Thanks,

**Comment by remarkablemark** [comment]
Hi @jackdh, do you mind sending me a simplified [fiddle](https://jsfiddle.net/remarkablemark/7v86d800/) so I can see what you're trying to do?

**Comment by remarkablemark** [comment]
@jackdh Do you mean something like this? https://jsfiddle.net/remarkablemark/txg6yc23/

**Comment by jackdh** [comment]
Hi @remarkablemark 

Sorry for the late reply. I'm afraid I no longer have the example as we went with a work around.

If it can't be replicated I'm happy for this issue to be closed.

Thanks.
