### ISSUE TITLE
Deep parsing with replace, readme example doesn't work

### ISSUE THREAD

**Issue by aaronbarker** [remarkablemark/html-react-parser#55]
This worked perfectly for the first level in my HTML, thank you! But children were not getting replaced. I even used your `prettify` example from the readme, and my output is:

```
<div>
    <span style="font-size: 42px;">
        <span class="prettify">
            keep me and make me pretty!
        </span>
    </span>
</div>
```
only getting the first replaced element, not both.

Am I misinterpreting your example, or is something broken?

**Comment by remarkablemark** [comment]
@aaronbarker I'm still able reproduce the expected output from the example--see [repl.it](https://repl.it/@remarkablemark/html-react-parser-advanced-example).

There is a minor error in that `options` should be `parserOptions` in the example. If you'd like to submit a fix, I would be happy to take a look =)

**Comment by remarkablemark** [comment]
Let me know if you're still having trouble with the example output--otherwise, I'll be closing this issue. Thanks @aaronbarker

**Comment by aaronbarker** [comment]
Awesome, thanks!
