### ISSUE TITLE
Exclude nodes with replace

### ISSUE THREAD

**Issue by nkrambo** [remarkablemark/html-react-parser#56]
Are there any plans to be able to easily exclude nodes entirely with the replace option?

Perhaps by returning `null`?

**Comment by nkrambo** [comment]
@remarkablemark That's actually a great solution, I didn't even think of that.

I'm not sure how useful it would actually be implementing a solution got <16 users. But perhaps, an updated docs around excluding nodes like this would be useful?

Thanks.

**Comment by remarkablemark** [comment]
Updating the docs sound like a great idea @nkrambo

Feel free to submit a PR if you'd like--otherwise, I can add the one used in our discussion

**Comment by nkrambo** [comment]
@remarkablemark - Sounds good. I'll get a PR your way.
