### ISSUE TITLE
domNode instanceof Element return false

### ISSUE THREAD

**Issue by ajjack50n** [remarkablemark/html-react-parser#578]
The latest release appears to have a problem..

expected:

`domNode instanceof Element` returns true for dom elements

actual: it returns false

code I am using below...
I will try and create a demo but no time right now....

```
const options: HTMLReactParserOptions | undefined = {
    replace: (domNode: DOMNode): JSX.Element | undefined => {
        if (
            domNode instanceof Element
            && domNode.attribs
        ) {
            ....
                return (
                    ...
                )
            }
        }
        return
    }
}

```

## Environment

- Version: 1 latest : 1.4.14
- Platform: 
- Browser: tried in chrome

**Comment by remarkablemark** [comment]
Can you try deleting `node_modules` and doing a fresh install?

```sh
rm -rf node_modules
npm i
```

**Comment by superchrisho** [comment]
I did a refresh install, also tried rolling back to previous versions. domNode instanceof Element is always false.

I managed to use the workaround suggested by @ajjack50n . 

`replace: (domNode) => {
              const el: Element = domNode as Element;

              if (el.name === "ul")...`

**Comment by superchrisho** [comment]
> So I rolled back to the previous version I was on but that did not fix it. I am a bit confused as to what has happened. Perhaps someone smarter than me on this forum can explain...
> 
> I have worked around the issue with the following..
> 
> ```
>         const el: Element = (domNode as Element)
>         if (el.attribs)...
> ```

I don't get it why "instanceof Element" doesn't work either. Thanks for the work around!

**Comment by remarkablemark** [comment]
It seems like the error is not showing up in the CodeSandbox: https://codesandbox.io/s/html-react-parser-z0kp6?file=/src/index.tsx

**Comment by remarkablemark** [comment]
@superchrisho has your issue been resolved? Can the issue be closed?

**Comment by superchrisho** [comment]
@remarkablemark 
Using the work around, it is resolved.

**Comment by remarkablemark** [comment]
Thanks! Closing issue.
