### ISSUE TITLE
Parse text nodes

### ISSUE THREAD

**Issue by loretoparisi** [remarkablemark/html-react-parser#58]
I have text nodes like `<span style="background-color:rgb(187,255,187)">Hello World!</span>` and I have tried like

```javascript
var parsedElem=HTMLReactParser(node.innerHTML);
var reactElem=React.createElement(parsedElem, {className: "span"});
ReactDOM.render(reactElem, this.overlay);
```

but the parsed element is the contents (i.e. the text of the node) not the `<span>` itself.

**Comment by loretoparisi** [comment]
I have solved it using _node.outerHTML_!

**Comment by remarkablemark** [comment]
Great to hear that you solved it!

**Comment by loretoparisi** [comment]
@remarkablemark thanks, I'm actually using your plugin for a React Chrome extension example here https://stackoverflow.com/questions/50813685/modify-react-app-in-chrome-extension

The example code is here https://github.com/loretoparisi/chrome-extension-react-app

maybe you can give me some hint about this 👍
