### ISSUE TITLE
SSR - crashes with "navigator is not defined"

### ISSUE THREAD

**Issue by Remownz** [remarkablemark/html-react-parser#59]
Hi,

in compiled "html-react-parser.js" is a function (isIE) which seems to be called only by importing your lib. On server side this function crashes my build due to unchecked existence of navigator.

"ReferenceError: navigator is not defined"

**Comment by remarkablemark** [comment]
Hi @Remownz, if I understand correctly, are you importing the library via:
```js
const Parser = require('html-recact-parser/dist/html-react-parser');
```

If so, the error is expected because you're importing the browser build of the library.

Is there any reason why you're unable to import the library via:
```js
const Parser = require('html-react-parser');
```

See [example](https://repl.it/@remarkablemark/html-react-parser).

**Comment by Remownz** [comment]
Hi @remarkablemark, 

no, i imported your package as usual:

`import HTMLStringParser from 'html-react-parser';`

On serverside a error was thrown by your lib ("ReferenceError: navigator is not defined"), so i checked where this error came from. I found the function (isIE) inside the compiled version of your lib.

**Comment by remarkablemark** [comment]
Hmm... that is very strange @Remownz

Could you create a repository or Gist that reproduces this error?

And any information pertaining to your OS, Node.js, and NPM/Yarn would be helpful as well.

**Comment by Remownz** [comment]
@remarkablemark sorry, i've no time for that and i already switched to another lib (react-html-parser). I just want to leave this issue here.

**Comment by remarkablemark** [comment]
No problem @Remownz. Since this issue cannot be reproduced on my side, can it be closed?

**Comment by bragovo** [comment]
I have problem with SSR too.
https://github.com/luckypike/lunn/blob/master/app/javascript/components/Footer/Footer.js - this is problem component. There is an error with `parse('<h1>Hello, world!</h1>')` too.

I can't find where is error exactly, that's my log:
```
Error during failsafe response: Encountered error "#<ExecJS::ProgramError: TypeError: Cannot read property 'a' of undefined>" when prerendering Footer/Footer with {"locale":"ru"}
Footer ((execjs):3532:72)
processChild ((execjs):27714:18)
resolve ((execjs):27637:9)
ReactDOMServerRenderer.render ((execjs):28095:26)
ReactDOMServerRenderer.read ((execjs):28033:33)
Object.renderToString ((execjs):28709:31)
Object.serverRender ((execjs):61902:42)
(execjs):6:45
(execjs):18:13
```

**Comment by bragovo** [comment]
`console.log(domToReact(htmlToDOM('<h1>HI!</h1>', {})))` - work fine.
But this one not working:
```
export default function Footer () {
  return (
    <>{domToReact(htmlToDOM('<h1>HI!</h1>', {}))}</>
  )
}
```
`Error during failsafe response: Encountered error "#<ExecJS::ProgramError: TypeError: Cannot read property 'domToReact' of undefined>" when prerendering Footer/Footer with {"locale":"ru"}`

**Comment by bragovo** [comment]
```
// No error

import React from 'react'
import { domToReact } from 'html-react-parser'

console.log(domToReact)

export default function Footer () {
  // console.log(domToReact)

  return (
    <></>
  )
}


// Error: TypeError: Cannot read property 'domToReact' of undefined>" when prerendering Footer/Footer with {"locale":"ru"}

import React from 'react'
import { domToReact } from 'html-react-parser'

// console.log(domToReact)

export default function Footer () {
  console.log(domToReact)

  return (
    <></>
  )
}
```

**Comment by bragovo** [comment]
Actually, simple `import parse from 'html-react-parser'` not working `Encountered error "#<ExecJS::ProgramError: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.>" when prerendering Footer/Footer`

**Comment by bragovo** [comment]
And as @Remownz says simple replace to `ReactHtmlParser` (from react-html-parser) instead `parse` working fine with SSR

**Comment by bragovo** [comment]
Seems problem in package `import htmlToDOM from 'html-dom-parser'`

**Comment by bragovo** [comment]
So, this is working:
```
import htmlparser2 from 'htmlparser2'
import domToReact from 'html-react-parser/lib/dom-to-react'

export default function Footer () {
  return (
    <div>
      {domToReact(htmlparser2.parseDOM('<h1>h1</h1>'))}
    </div>
  )
}
```

**Comment by remarkablemark** [comment]
@bragovo Are you trying to build this library on Ruby/Rails?

I'm able to do SSR (server-side rendering) on Node.js without any issues. See [Repl.it](https://repl.it/@remarkablemark/html-react-parser-SSR).
