### ISSUE TITLE
How get acces to children 'data' property with TypeScript

### ISSUE THREAD

**Issue by meesfrenkelfrank** [remarkablemark/html-react-parser#591]
I need to replace something and try to use it like:

```
const options: HTMLReactParserOptions = {
    replace: (domNode) => {
      if (domNode instanceof Element && domNode.type === 'script' && domNode.children.length) {
        // ...
        console.log('hi', domNode.children[0].// <- here `data` is not accessible'?);
      }
    },
  };

  return (
    <div>
      {parse(html, options)}
    </div>
  );
```

From Eslint I get:
> Property 'data' does not exist on type 'Node'.

How do I get acces to children `data` property?

So I am able to do something like:

`domNode.children[0].data.includes('Some string')`

**Comment by remarkablemark** [comment]
Is this a TypeScript question?

I was able to get `data` in this Replit: https://replit.com/@remarkablemark/html-react-parser-591

**Comment by meesfrenkelfrank** [comment]
@remarkablemark yeah it's a TypeScript issue. When I try this:

```
const options: HTMLReactParserOptions = {
    replace: (domNode) => {
      if (domNode instanceof Element && domNode.type === 'script' && domNode.children.length) {
        console.log(domNode.children[0].data);
        // console.log(domNode.firstChild);
      }
    },
  };
```

I get this TypeScript error:

```
Property 'data' does not exist on type 'Element | (Node & Element)'.
  Property 'data' does not exist on type 'Element'.ts(2339)
```

**Comment by remarkablemark** [comment]
Ah gotcha, I recommend using type assertion:

```ts
import type { Node } from 'html-react-parser';

// ...
(domNode.children[0] as Node).data
```

**Comment by meesfrenkelfrank** [comment]
@remarkablemark thanks. I think `Node` doesn't has `data` property. I got it working with:

```
import parse, { HTMLReactParserOptions, Element, Node, Text } from 'html-react-parser';

((domNode.children[0] as Node) as Text).data
```

Is this the only and cleanest solution?

**Comment by remarkablemark** [comment]
@meesfrenkelfrank yeah that might be the solution. If that works, feel free to close the issue!

**Comment by heikkikesa** [comment]
I had this same issue.
But there's no need to first assert it to `Node`, just go for the `Text`.
Like this: `(domNode.children[0] as Text).data`

**Comment by meesfrenkelfrank** [comment]
Thanks indeed thats working fine. I will close the issue.
