### ISSUE TITLE
Fails on createElements that doesn't exist

### ISSUE THREAD

**Issue by davesnx** [remarkablemark/html-react-parser#60]
Hey @remarkablemark,

I'm working on a project where we can't control the user input and we rely on that to create some React elements, like bold/italic and this kind of stuff.

So, we are running into a problem when the input looks like: `<c&/>` or any non-valid html tag, but still looks like someone is trying to parse it.

```
Failed to execute 'createElement' on 'Document': The tag name provided ('c&') is not a valid name.
```
and it comes from ReactDOM, so I suspect that we are sending down to React non-valid html tags, for instance, containing `&`. 

I created an example to explain it better: https://codesandbox.io/s/z21yv25y0p

Considering that `html-react-parser` uses `html-dom-parser`, I tried directly what's the actual parsing result from `<c&/>` and looks valid: 

```js
/*
  [Object]
    0: Object
    next: null
    prev: null
    parent: null
    name: "c&"
    attribs: Object
    type: "tag"
    children: Array[1]
      0: Object
      next: null
      prev: null
      parent: Object
      next: null
      prev: null
      parent: null
      name: "c&"
      attribs: Object
      type: "tag"
      children: Array[1]
        type: "text"
        data: " CodeSandBo0o0o0ox"
 */
```

Let me know if you need more info about this.
Thanks!

**Comment by davesnx** [comment]
I'm using latest `html-react-parser` (`0.4.6`) and latest `react` (`16.4.0`).

Probably adding a validation into what's a valid html tag, as a whitelisting what's allowed; or actually, the other way arround, blacklisting the characters non-valid.

**Comment by remarkablemark** [comment]
@davesnx Thanks for opening the issue with a detailed explanation and reproducible example. You're right that `html-react-parser` and `html-dom-parser` do not validate tag names. That is actually expected behavior.

If you're dealing with user input in which you need to validate it yourself, have you tried using the [`replace`](https://github.com/remarkablemark/html-react-parser#replacedomnode) option?

[Example](https://repl.it/@remarkablemark/html-react-parser-issue-60):
```js
Parser('<c&></c&> CodeSandBo0o0o0ox', {
  replace: ({ name }) => {
    if (!/^[a-zA-Z]+[0-9]?$/.test(name)) {
      return React.createElement(React.Fragment);
    }
  },
});
```

As explained in #56, you can exclude nodes from the parsed output. Let me know if that helps.

**Comment by davesnx** [comment]
Thanks for the response @remarkablemark 

On my site... just replaced the `<` & `>` to HTML entities, so '&lt;' and '&lt;'. Works pretty well for my case. 

I just opened this because I didn't expect to be the expected behaviour.

👍

**Comment by remarkablemark** [comment]
@davesnx Gotcha that makes sense.

So since this is expected behavior, can this issue to be closed? Or do you think it's useful to document this somewhere like in the `README.md`?

**Comment by davesnx** [comment]
Nah, I will close it.
