### ISSUE TITLE
Passing object for string isn't returning anything

### ISSUE THREAD

**Issue by ConduciveMammal** [remarkablemark/html-react-parser#601]
## Expected Behavior

When passing an object via a component prop, I should be able to parse the object's keys into a string.

## Actual Behavior

Returns nothing at all.

## Steps to Reproduce

Pass an object as a prop into a component, and then access individual keys in a string template.
```javascript
<Component
  tag={{text: 'Hello world', color: 'red'}}
>

// Inside component
...{ReactHtmlParser(`<strong class="tag--${tag.color}>${tag.text}</strong>`
```

## Reproducible Demo
https://codesandbox.io/s/jolly-breeze-geoksi

In the demo, you can see that I am passing an object `tag={{ text: "Recommended", color: "orange" }}`. Within the component, I'm using html-react-parser as
```javascript
{ReactHtmlParser(
        `<strong class="product-card__tag test product-card__tag--${tag.color}>${tag.text}</strong>`
      )}
```

Yet simply doesn't render anything at all.

## Environment

- Version:  2.0.2
- Platform: Shopify
- Browser: Chrome 102.0.5005.115

**Comment by remarkablemark** [comment]
@ConduciveMammal you may have opened this issue in the wrong repository since this is `html-react-parser`, not [react-html-parser](https://github.com/peternewnham/react-html-parser)

**Comment by ConduciveMammal** [comment]
Aha bother! Apologies for that.

**Comment by remarkablemark** [comment]
No worries! Closing issue.
