### ISSUE TITLE
Injecting variables from state or props

### ISSUE THREAD

**Issue by Typiqally** [remarkablemark/html-react-parser#606]
I was wondering if it was possible to inject properties from the state or props object within the HTML result. Refer to the following example:

```ts
interface IState {
    name: string;
}

const [state] = useState<IState>({name: "Example"});

parse("<p>Hello, world, {{state.name}}</p>");

// Should result in <p>Hello, world, Example</p>
```

I'm unable to find any examples online, nor in the previous issues.

**Comment by Typiqally** [comment]
Sadly not, I'm attempting to load templates from an external REST API, which come in the form of HTML documents.

I'm not sure whether there is a better way, but I want to refrain from generating the document on the API side requiring me to send a request for every update and keep the templating in my frontend with state watchers.

**Comment by remarkablemark** [comment]
Can you transform your raw HTML with something like [mustache](https://github.com/janl/mustache.js/)?

Or even use replace?

```ts
const template = '<p>Hello, world, {{ name }}</p>';
const html = template.replace('{{ name }}', state.name);
parse(html);
```

**Comment by Typiqally** [comment]
That could definitely work with this package called `mustache`. Knowing that, am I right in assuming this means that this package does not support this natively?

**Comment by remarkablemark** [comment]
Yes `html-react-parser` does not support templating. It only supports converting HTML to React elements.
