### ISSUE TITLE
Request parse return null instead of throwing

### ISSUE THREAD

**Issue by rlgordey** [remarkablemark/html-react-parser#607]
I would like to request that if something null is passed into `parse` then return null instead of throwing.

For example I have to initialize my state variable like this:

```
this.state = {            
            ribbon: { ribbonText: "Loading"}
        };
```

Then load it from database in `componentDidMount`
```
async componentDidMount() {
        var request = await fetch(Config.apiUrl + "/api/Header/GetRibbon");
        var result = await request.json();
        this.setState({ ribbon: result });             
}
```

So I can call `parse` like this:
```
<p>{parse(this.state.ribbon.ribbonText)}</p>
```

**Comment by remarkablemark** [comment]
Can you pass empty string if you don't want it to throw?

**Comment by rlgordey** [comment]
@remarkablemark  Aye, I can. What I have works. I am trying to be lazy so I can initialize like this: `ribbon: { }`

**Comment by remarkablemark** [comment]
@rlgordey gotcha then can you do this?

```tsx
<p>{parse(this.state.ribbon.ribbonText || '')}</p>
```

**Comment by rlgordey** [comment]
@remarkablemark  Thanks for the help. And I learned a new JavaScript trick as well.

**Comment by remarkablemark** [comment]
Nice! @rlgordey
