### ISSUE TITLE
que: use cases

### ISSUE THREAD

**Issue by apatel369** [remarkablemark/html-react-parser#610]
what are the use cases of html-react-parser?

I cannot figure out where and why I need it.

**Comment by remarkablemark** [comment]
One scenario is if you have raw HTML that you want to render in a React app but you also want to replace an element.

**Comment by apatel369** [comment]
I know what it does but where can I use it practically?

**Comment by remarkablemark** [comment]
A real world example is if you're using WordPress and it returns HTML in an API response and you are building a React UI and you want to replace a placeholder element with a custom component.

**Comment by apatel369** [comment]
Makes sense. Thanks
