### ISSUE TITLE
<body> tag with newline symbols doesn't get parsed

### ISSUE THREAD

**Issue by Dremora** [remarkablemark/html-react-parser#624]
## Expected Behavior

`"<body \n>hello</body>"` gets parsed as it is. I've checked W3C HTML validator, and this is valid HTML. Strangely enough, the bug only applies to `<body>`.

## Actual Behavior

No body is returned.

## Steps to Reproduce

Try parsing the following string:
```html
  <!DOCTYPE html>
  <html>
    <head>
      <title>Working</title>
    </head>
    <body
    >hello world</body>
  </html
```

## Reproducible Demo

[Codesandbox](https://codesandbox.io/s/friendly-shirley-nx9mej)

## Environment

- Version: 3.0.0 (also tried on 1.4.0)
- Platform: macOS 12.3.1
- Browser: Chrome 103

**Comment by remarkablemark** [comment]
Thanks for opening this issue @Dremora. I can confirm this bug in [CodeSandbox](https://codesandbox.io/s/html-react-parsser-624-p0i5pd?file=/src/App.js) with the HTML string:

```html
<head></head>
<body
>text</body>
```

The bug is coming from https://github.com/remarkablemark/html-dom-parser/issues/317

**Comment by remarkablemark** [comment]
Release https://github.com/remarkablemark/html-react-parser/pull/627#issuecomment-1179825046
