### ISSUE TITLE
Nested nodes overwritten by parent domNode

### ISSUE THREAD

**Issue by opr-inzn** [remarkablemark/html-react-parser#648]
I’m trying to parse some text from a CMS, that comes in the following structure:

`<p><strong></strong><em></em></p>`

I’m using the replace function with domToReact and it currently looks like this:

```
replace: (domNode) => {
  if (domNode.name === "p") {
    return (
      <p className="text-3xl">
        {domToReact(domNode.children)}
      </p>
    );
  }
  if (domNode.name === "strong") {
    return (
      <span className="underline">
        {domToReact(domNode.children)}
     </span>
    );
  }
}
```

My issue here is, that the `<strong>` replace does not get applied, only the `<p>` does. How does this work when having nested nodes? 

Thanks in advance!

**Comment by remarkablemark** [comment]
@opr-inzn You'll need to change the order of the replace so move the `if (domNode.name === "strong")` conditional before the `if (domNode.name === "p")`. It should work after that.

**Comment by opr-inzn** [comment]
@remarkablemark I thought so too, but unfortunately this does not work! 

```
[Log] Element
attribs: {}
children: Array (1)
0 Element
attribs: {}
children: [Text] (1)
endIndex: null
name: "strong"
next: null
parent: Element {parent: null, prev: Text, next: null, startIndex: null, endIndex: null, …}
prev: null
startIndex: null
type: "tag"
Element Prototype
Array Prototype
endIndex: null
name: "p"
next: null
parent: null
prev: Text {parent: null, prev: Element, next: Element, startIndex: null, endIndex: null, …}
startIndex: null
type: "tag"
Element Prototype
```

The parse/replace function now looks like this:
```
{parse(data.about.biography, {
              replace: (domNode) => {
                console.log(domNode);

                if (domNode.name === "strong") {
                  return (
                    <span className="underline">
                      {domToReact(domNode.children)}
                    </span>
                  );
                }
                if (domNode.name === "p") {
                  return (
                    <p className="[&_+p]:mt-4 md:[&_+p]:mt-6 leading-[1.3]">
                      {domToReact(domNode.children)}
                    </p>
                  );
                }
              },
            })}
```

And in the dom, this gets rendered:
<img width="632" alt="Screenshot 2022-08-11 at 10 44 06 AM" src="https://user-images.githubusercontent.com/80823111/184096549-8d620b9c-3969-4dc9-b6b1-33fcd84fdb72.png">

**Comment by remarkablemark** [comment]
Gotcha can you provide a reproducible example using [CodeSandbox](https://codesandbox.io/s/940pov1l4w)?

**Comment by opr-inzn** [comment]
@remarkablemark sure! Hope this is working: [https://codesandbox.io/s/youthful-vaughan-ppxs95?file=/pages/index.js](https://codesandbox.io/s/youthful-vaughan-ppxs95?file=/pages/index.js)

**Comment by remarkablemark** [comment]
@opr-inzn thanks for sharing the example. The issue was that you need to pass the replace `options` from `parse` to `domToReact`. See https://codesandbox.io/s/html-react-parser-648-lc94gl?file=/pages/index.js

**Comment by opr-inzn** [comment]
That works, thanks!!
