### ISSUE TITLE
Replace img tag with img Component

### ISSUE THREAD

**Issue by pddt1** [remarkablemark/html-react-parser#651]
Can I replace img tag with React Component( like `<LazyImg src={attribs.src} />`) ?
I have tried but it returned span tag.

**Comment by remarkablemark** [comment]
Yes you can use the [replace](https://github.com/remarkablemark/html-react-parser/tree/v3.0.1#replace) option. Can you show me an example where it's not returning the correct element?

**Comment by pddt1** [comment]
> Yes you can use the [replace](https://github.com/remarkablemark/html-react-parser/tree/v3.0.1#replace) option. Can you show me an example where it's not returning the correct element?

This is when it's rendered: 
![image](https://user-images.githubusercontent.com/91549883/184548419-51a85548-9a37-40d8-a123-e58cc67412e2.png)
This is my example code:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/91549883/184548497-a8e8e442-1479-463a-8de3-e82105d6b4ff.png">
I think the problem is LazyLoadImg component has 2 elements when it's rendered

**Comment by pddt1** [comment]
The input content is something like
`<div><img src=.../><img src=.../><div/>`
`<div><img src=.../><div/>`

**Comment by remarkablemark** [comment]
Hmm I might need your help in creating a [CodeSandbox](https://codesandbox.io/s/940pov1l4w) example for me to tell what the actual issue is

**Comment by pddt1** [comment]
I have solved. It's a problem from another library I used. Thanks
