### ISSUE TITLE
break line tag </br> is not supported?

### ISSUE THREAD

**Issue by ShaiMahnai** [remarkablemark/html-react-parser#652]
when I run **`parse("a<br/>b")`** it's render:
`ab`

when i run **`parse("a<br>b")}`** it's render: 
`a`
`b`

why is the different?  
`<br/>` is a valid tag in browser and should break link as well.

**Comment by remarkablemark** [comment]
What version are you using? Can you provide a reproducible [example](https://github.com/remarkablemark/html-react-parser/tree/v3.0.1#example)? This may be related to [html-dom-parser](https://github.com/remarkablemark/html-dom-parser)
