### ISSUE TITLE
./node_modules/html-dom-parser/lib/client/html-to-dom.mjs Can't import the named export 'formatDOM' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Narenderb** [remarkablemark/html-react-parser#662]
## Expected Behavior

it should not through any error while installing the library

## Actual Behavior
We are getting an error while installing the library

## Environment

- Version:
- Platform:
- Browser:

**Comment by remarkablemark** [comment]
@Narenderb can you provide a reproducible example?

**Comment by michielkramer** [comment]
We have the same issue. Occurred after upgrading to Node 16.
Version: 3.0.1
Win 10
Chrome 104.0.5112.82

**Comment by remarkablemark** [comment]
@michielkramer can you provide a reproducible example? Also, have you tried upgrading to latest version `3.0.3`?

```sh
npm i html-react-parser@latest
```

**Comment by remarkablemark** [comment]
Release https://github.com/remarkablemark/html-react-parser/pull/668#issuecomment-1223383096
