### ISSUE TITLE
Tag attributes are getting converted to lower case

### ISSUE THREAD

**Issue by matthewnitschke** [remarkablemark/html-react-parser#67]
When parsing a dom element with mixed case attribute names, the resulting react module has both the component name and attribute names to lower case. I understand the component name getting set to lower case is mentioned in #62, but the attributes also getting set to lowercase seems like a bug due to this line: https://github.com/remarkablemark/html-react-parser/blob/97d6868/index.js#L5 which specifically specifies to not lowercase attribute names.

Is a bug in `htmlparser2`? or is there some issue with this module?

**Comment by remarkablemark** [comment]
@matthewnitschke Can you help me reproduce your case? See [Repl.it](https://repl.it/@remarkablemark/html-react-parser-issue-67)

**Comment by matthewnitschke** [comment]
Ah, it appears as though my problem is only repeatable when using custom react components within the parse string. Correct me if I am wrong but I don't think this library is meant to handle that case

**Comment by matthewnitschke** [comment]
Alright, thank you for your help
