### ISSUE TITLE
[NextJS] Compilation fails during build

### ISSUE THREAD

**Issue by hali241997** [remarkablemark/html-react-parser#684]
## Expected Behavior
After running `next build` command, the build should compile without any errors

## Actual Behavior
Failed to compile when run `next build` but it works in development
This is the error:
```
../../node_modules/htmlparser2/lib/index.d.ts:2:23
Type error: ',' expected.

  1 | import { Parser, ParserOptions } from "./Parser.js";
> 2 | export { Parser, type ParserOptions };
    |                       ^
  3 | import { DomHandler, DomHandlerOptions, ChildNode, Element, Document } from "domhandler";
  4 | export { DomHandler, type DomHandlerOptions };
  5 | declare type Options = ParserOptions & DomHandlerOptions;
```
## Steps to Reproduce
1. Install `html-react-parser@^3.0.4`.
2. Use the parser config option.
3. Run `next build`

## Environment

- Version: 3.0.4
- Platform: NextJS
- Browser: Chrome

**Comment by remarkablemark** [comment]
@hali241997 can you provide a reproducible example?

**Comment by hali241997** [comment]
Hi @remarkablemark Here's a reproducible example:
https://codesandbox.io/s/html-react-parser-issue-v3rnw4

It's not loading up correctly due to some issue with babel. For some reason, I can't figure out that issue. But if you run `yarn build`, you will get the same issue that I am experiencing

**Comment by remarkablemark** [comment]
Thanks for providing the reproducible example. I can confirm your error when running `yarn build` in my [fork](https://codesandbox.io/s/html-react-parser-issue-forked-rc0qq4):

```
./node_modules/htmlparser2/lib/index.d.ts:2:23
Type error: ',' expected.

  1 | import { Parser, ParserOptions } from "./Parser.js";
> 2 | export { Parser, type ParserOptions };
    |                       ^
  3 | import { DomHandler, DomHandlerOptions, ChildNode, Element, Document } from "domhandler";
  4 | export { DomHandler, type DomHandlerOptions };
  5 | declare type Options = ParserOptions & DomHandlerOptions;
```

It looks like it's coming from `htmlparser2`, which is a package separate from this library. I'm not sure what I can do on my end to fix this.

This error may be related to your custom babel config. Question: are you able to use the default TypeScript config provided by Next.js?

**Comment by hali241997** [comment]
Hi @remarkablemark as per the dependency graph [here](https://npm.anvaka.com/#/view/2d/html-react-parser), the `htmlparser2` is a dependency of `html-react-parser`
And yes, I was able to use the default Typescript config provided by Nextjs.

**Comment by remarkablemark** [comment]
You are correct about the dependency graph. But I'm not sure what I can do on my end to fix this. For example, if lodash is in the dependency graph of this library and there is a bug on lodash, am I responsible for it?

**Comment by hali241997** [comment]
Seems fair enough, I'll open the issue with `htmlparser2`. Thank you for the help
