### ISSUE TITLE
Reduce import size?

### ISSUE THREAD

**Issue by jason-humu** [remarkablemark/html-react-parser#689]
Hi, I really love this tool, and am very grateful for all the work gone into it. 🥰

**Is there a way to reduce the import size?**  My editor is showing a very large addition to the client bundle.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/107440558/188792126-7e4b6cf6-58c1-4a11-be67-d666f12c5571.png">

**Comment by remarkablemark** [comment]
What bundler did you use? It should be smaller:

- 26.8 kB MINIFIED
- 9.7 kB MINIFIED + GZIPPED

https://bundlephobia.com/package/html-react-parser@3.0.4

**Comment by jason-humu** [comment]
Apologies and you're right, this is pre-bundle sizes.
