### ISSUE TITLE
Vulnerable Dependency [atob   2.0.3]

### ISSUE THREAD

**Issue by intivemark** [remarkablemark/html-react-parser#70]
(+) 1 vulnerability found

| Name        | Installed           | Patched  | Path | More info |
| ---------- |--------------- | --------- |----- | --------- |
| atob      | 2.0.3 | >=2.1.0  | html-react-parser@0.4.6 > style-to-object@0.2.1 > css@2.2.3 > source-map-resolve@0.5.1 > atob@2.0.3  | https://nodesecurity.io/advisories/646 |

**Comment by remarkablemark** [comment]
Thanks for opening the issue @intivemark.

Luckily, [`style-to-object`](https://github.com/remarkablemark/style-to-object) is using [`css/lib/parse.js`](https://github.com/remarkablemark/style-to-object/blob/master/index.js#L1), which is not impacted by the vulnerability. tThe vulnerable module is [`lib/stringify/source-map-support.js`](https://github.com/reworkcss/css/search?q=source-map-resolve&unscoped_q=source-map-resolve) which is not used here.

Nevertheless, I'll look into upgrading the dependencies when I can a chance today or tomorrow.

**Comment by intivemark** [comment]
@remarkablemark That is remarkable :), thanks for solving this issue. I'm looking forward to the release so I can update my package.json and get rid of CI warnings.

Thanks for taking care 🎉

**Comment by remarkablemark** [comment]
@intivemark No problem, glad to be of help.

You can install the latest version:
```sh
# with npm
$ npm install --save html-react-parser@0.4.7

# with yarn
yarn add html-react-parser@0.4.7
```
