### ISSUE TITLE
Parsing an html with invalid html tags , like <test@email.com> makes the whole app crash.

### ISSUE THREAD

**Issue by GiorgosSpil** [remarkablemark/html-react-parser#733]
## Expected Behavior
When an invalid html tag exists in the parsing string I expected to parse the html as usual and leave invalid elements as strings.
(At least what I expected)
## Actual Behavior
If an invalid html tag is in the string like <something> . When parse is called the library breaks and then the whole app crashes.
## Steps to Reproduce
Try parsing an invalid html tag like , <tag@test.com> 
## Environment
- React version : 17.0.2
- Version:3.0.4
- Platform: Windows 10
- Browser:Google Chrome

**Comment by remarkablemark** [comment]
Thanks for opening this issue @GiorgosSpil! Can I get your help in creating a reproducible example using [CodeSandbox](https://github.com/remarkablemark/html-react-parser#example)?

**Comment by GiorgosSpil** [comment]
Hello  , this  is the problem reproduced. So, when passing an invalid html
(unsanitzed) the library breaks

Στις Πέμ 27 Οκτ 2022 στις 8:53 μ.μ., ο/η Mark ***@***.***>
έγραψε:

**Comment by GiorgosSpil** [comment]
https://codesandbox.io/s/keen-tharp-982jfg

Στις Πέμ 27 Οκτ 2022 στις 9:19 μ.μ., ο/η Giorgos Spiliotopoulos <
***@***.***> έγραψε:

**Comment by remarkablemark** [comment]
Thanks for providing the reproduced example!

This is expected behavior as invalid HTML is not sanitized. I recommend sanitizing your HTML first.

See [Does invalid HTML get sanitized?](https://github.com/remarkablemark/html-react-parser/tree/v3.0.4#does-invalid-html-get-sanitized)
