### ISSUE TITLE
How to convert React.component to html string?

### ISSUE THREAD

**Issue by xanxus135** [remarkablemark/html-react-parser#769]
Hello.

I want to convert components from the **parse** function to an Html string.
I tried to use **renderToStaticMarkup** to convert, but it threw an error.

Have any other ideas to do it?

**Comment by remarkablemark** [comment]
If it's already already a React element, [renderToStaticMarkup](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup) should work. I think it's better to ask this question in [Stackoverflow](https://stackoverflow.com/) since it's unrelated to this library.
