### ISSUE TITLE
Doesn't work with web components with custom attributes

### ISSUE THREAD

**Issue by bschlenk** [remarkablemark/html-react-parser#77]
If I pass in an html string with attributes this doesn't recognize, they are not included in the props.

```jsx
<my-custom-element label="mylabel" my-custom-prop="someValue"></my-custom-element>
```

This will only include `label`, but not `my-custom-prop`.

**Comment by bschlenk** [comment]
Here’s the issue where they talk about supporting any attribute for custom elements: https://github.com/facebook/react/issues/2746

It looks like it’s  been supported since React 0.14.

**Comment by remarkablemark** [comment]
I didn't realize React made the change in 16+, thanks for sharing the link @bschlenk

I'm open to making a backwards compatible change to allow for this

**Comment by bschlenk** [comment]
To make it backwards compatible it would probably have to check what version of react is installed. I'm not sure on the exact logic, but here's what I'm thinking:

if react.version >= 16:
  if isCustomElement:
    don't alter props at all
  else:
    alter props as usual, but also pass any unrecognized props unaltered
else:
  same logic as before

I made these changes on my machine, I can send you a pull request once I get tests written.

**Comment by remarkablemark** [comment]
`html-react-parser@0.5.0` was released:

You can install the version:

```sh
# with npm
$ npm install --save html-react-parser@0.5.0

# or with yarn
yarn add html-react-parser@0.5.0
```

Thanks for the adding this feature @bschlenk!

**Comment by sinchang** [comment]
seems doesn't work if web components have style attributes.

```
```

**Comment by remarkablemark** [comment]
@sinchang Can you help me provide a reproducible example with [CodeSandbox](https://codesandbox.io/s/940pov1l4w), [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/), or [Repl.it](https://repl.it/@remarkablemark/html-react-parser)?

If we can confirm this is a bug, let's create a new issue.

**Comment by sinchang** [comment]
@remarkablemark I created a demo on https://codesandbox.io/s/html-react-parser-forked-vll1t?file=/src/index.js:281322-281329, please have a look.

**Comment by remarkablemark** [comment]
@sinchang Can you open a new issue and update your demo so `html-react-parser` only parses the HTML:

```html
<share-widget-desktop style="display: none; position: absolute;"></share-widget-desktop>
```

Since that's enough to reproduce the bug?
