### ISSUE TITLE
Export `Text` from `domhandler`

### ISSUE THREAD

**Issue by harryzcy** [remarkablemark/html-react-parser#777]
## Expected Behavior

```import { Text } from 'html-react-parser'``` should work

## Actual Behavior

It fails because `Text` is only exported in type definition, but not in `index.js` file.

## Steps to Reproduce

```import { Text } from 'html-react-parser'```

## Environment

- Version: v3.0.4
- Platform: macOS
- Browser: Chrome

**Comment by remarkablemark** [comment]
Additional `domhandler` classes have been exported in #780

**Comment by remarkablemark** [comment]
Release 3.0.5:

- https://github.com/remarkablemark/html-react-parser/pull/781#issuecomment-1364733881
