### ISSUE TITLE
Versions after 3.0.4 are breaking on projects without node module resolution

### ISSUE THREAD

**Issue by csrapr** [remarkablemark/html-react-parser#807]
My project has no node module resolution support so we are limtied to only UMD modules. We use this library and had to copy `html-react-parser/dist/html-react-parser.js` to our Libraries folder. Unfortunately, after the most recent changes after 3.0.4, we have an error when trying to load the library:
`exports is not defined Evaluating https://******/POS/Extensions/******/Libraries/html-react-parser.js` and we think the error is at line 13 where it has `exports["default"] = {};`
Is it possible for you to include a UMD version of this library in future releases? Thank you :)

**Comment by remarkablemark** [comment]
@csrapr Has the issue been resolved?

**Comment by paulronla** [comment]
Earlier in the day before 3.0.9 was released, I just happened to use 3.0.8 in the same way as OP and ran into the same issue. Version 3.0.9 doesn't have this issue for me and appears to be working. Thank you for the fix and this awesome parser!

**Comment by remarkablemark** [comment]
@paulronla Awesome, thanks for letting me know that 3.0.9 (https://github.com/remarkablemark/html-react-parser/pull/830) fixed it.
