### ISSUE TITLE
 support custom style properties '--*' (see https://drafts.csswg.org/css-variables/ for more information)

### ISSUE THREAD

**Issue by samikarak** [remarkablemark/html-react-parser#81]
Hello,

Our current application requires to use custom styles, so I would like to parse custom styles beginning with '--*' without camelCasing the first character after the second dash, so that the parser is compliant to [csswg specs for custom styles](https://drafts.csswg.org/css-variables/).
(info : it is also good to know, that react does only support custom styles beginning with '--*' )

I looked into the library files and found html-react-parser/lib/utilities.js which contains the function camelCase. This function is (obviously) responsible for mistakenly converting double dashed styles into camelCases. So for example '--customstyle' gets converted to '-Customstyle'.

besides checking if the string does not contain a dash, it could also be checked if the string is a custom style first.

```
  // customStyle or no hyphen found
  if (string.startsWith('--') || string.indexOf('-') === -1) {
    return string;
  }
```

this change would easily solve our problems

**Comment by samikarak** [comment]
> Also, do you mind sending me the source in which React says it supports CSS variables?

Since CSS variables are only supported by Firefox, I am not really interested in them. For me its about using custom style properties to select them via CSS selectors. And those are supported in reactjs. You can actually just try it out in the render function
```
render(){
   return <div style={{'--customStyle':'value'}}>the custom style will be visible in dom</div>
}
```
I couldn't find anything specific related to this, but maybe also because it is a CSS issue.

**Comment by remarkablemark** [comment]
Ah I misspoke earlier. I meant to say **custom properties** (not **CSS variables**).

It's ok if you couldn't find the specific documentation regarding React's support of it.

**Comment by remarkablemark** [comment]
@samikarak Thanks for taking the time to create the pull request!

I've released [html-react-parser](https://www.npmjs.com/package/html-react-parser) **v0.6.0**:

```sh
# to install with npm
$ npm install --save html-react-parser@0.6.0

# to install with yarn
yarn add html-react-parser@0.6.0
```
