### ISSUE TITLE
Argument not optional domparser.js on internet explorer

### ISSUE THREAD

**Issue by ghifari-ti** [remarkablemark/html-react-parser#826]
## Expected Behavior
website should show normally

## Actual Behavior

internet explorer show argument not optional domparser.js

## Environment

- Version: 3.0.8
- Platform:
- Browser: internet explorer 11
- OS: windows 10

## Note
this issue was solved by added null parameter on createHtmlDocument() function

**Comment by remarkablemark** [comment]
This is expected behavior since [IE is no longer supported since v2](https://github.com/remarkablemark/html-react-parser/tree/v3.0.8#v200).

If you want to support IE 11, you will need to downgrade to v1.

**Comment by ghifari-ti** [comment]
> This is expected behavior since [IE is no longer supported since v2](https://github.com/remarkablemark/html-react-parser/tree/v3.0.8#v200).
> 
> If you need IE 11 support, you'll need to downgrade to v1.

Thanks for the information
