### ISSUE TITLE
Copy html has so many new lines

### ISSUE THREAD

**Issue by Merynek** [remarkablemark/html-react-parser#843]
I have this input (from text editor)
![image](https://user-images.githubusercontent.com/6883795/220607849-8344b5f7-4951-42b9-921b-bf95cccc1680.png)

When i render it looks good:
![image](https://user-images.githubusercontent.com/6883795/220607980-012a71cd-bc84-44c9-b8ef-37d8de99fd1a.png)

But when I copy this code from browser by mouse selection and copy (ctrl + c) and paste => it has so many new lines
![image](https://user-images.githubusercontent.com/6883795/220608297-999f1115-3ba0-458a-a438-892c360c0102.png)
Is anybody know how can I fix this? I need only new lines that are same in input.
Its very bad when I copy some content in my WEB  and try paste it anywhere with many new lines.

Thx :-)

**Comment by remarkablemark** [comment]
Thanks for opening this issue @Merynek. Can you provide a reproducible example (e.g., [CodeSandbox](https://codesandbox.io/s/html-react-parser-z0kp6)) so I can verify the parser is causing this issue?

**Comment by Merynek** [comment]
I found out that its on my side issue (styles).
I am so sorry about this issue :-)
