### ISSUE TITLE
When using the parser to convert `<template>`, the document fragment content is empty.  Is there a way to get access to that data?

### ISSUE THREAD

**Issue by TimeDropsSB** [remarkablemark/html-react-parser#849]
## Question

Consider this code snippet:

```tsx
HTMLReactParser(`<template><article><p>Test</p></article></template>`);
```

When using the parser to convert this string with `<template>`, the document fragment content for it is empty.  The HTML `<template>` holds the inner elements within a document fragment and html-react-parser doesn't seem to replicate that data over.  Is there any way to get access to that data?

For reference, it should contain this when inspecting the DOM:

![image](https://user-images.githubusercontent.com/1796078/222845818-e7bc840b-4ffb-44b4-824b-a2637ffaf540.png)

## Keywords

html, template, document, fragment

**Comment by remarkablemark** [comment]
Thanks for opening this issue @TimeDropsSB! I was able to reproduce this in [CodeSandbox](https://codesandbox.io/s/html-react-parser-849-dxw8xv?file=/src/index.tsx) and confirm the bug in https://github.com/remarkablemark/html-dom-parser/issues/414

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/851#issuecomment-1454312460
