### ISSUE TITLE
Whitespace text nodes cannot appear as a child of <table>

### ISSUE THREAD

**Issue by benbesuijen** [remarkablemark/html-react-parser#85]
When I want to create a React table from a multi line string I will get an error from React:

`index.js:1452 Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code.`

**Example code that will trigger the error**
```jsx
render() {
  const table = parser.parse(`
    <table>
      <tbody>
        <tr>
          <td>Lorem Ipsum</td>
        </tr>
      </tbody>
    </table>
  `);

  return (
    <React.Fragment>
      {table}
    </React.Fragment>
  );
```

Off course I can fix this error by writing the table on one line, but that is not the solution where I'm looking for. 
`const table = parser.parse('<table><tbody><tr><td>Lorem Ipsum</td></tr></tbody></table>');`

With `dangerouslySetInnerHTML` I can use a multi line string without any problems. I also tried the package `html-to-react` but it will have the same problem.

Thanks for your time and help,
Ben

**Comment by remarkablemark** [comment]
This warning is expected when there's whitespace between table tags. (But just to clarify, this isn't an error and your elements should still render correctly.)

Currently, the best option is to strip off the whitespace if you have control over the string markup or use `dangerouslySetInnerHTML`.

Alternatively, you could try using [replace](https://github.com/remarkablemark/html-react-parser#replacedomnode) with `html-react-parser/lib/dom-to-react.js`.

**Comment by benbesuijen** [comment]
Yes you are right, it is a warning and not an error. It will be great if your package can take this over to separate parse logic from an application. But on the other hand maybe React is too strict with this warning. For now I use dangerouslySetInnerHTML to avoid warnings.

**Comment by remarkablemark** [comment]
Closing the issue now the question has been answered.
