### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length') in version 3.0.11 on nextjs project

### ISSUE THREAD

**Issue by huykon** [remarkablemark/html-react-parser#855]
## Expected Behavior
use parse without error

## Actual Behavior
![image](https://user-images.githubusercontent.com/9253798/223053378-053d87e6-46e9-446b-bafe-9ebdc8bf5d34.png)

## Steps to Reproduce
1. install the lib on nextjs project

## Environment

- Version: 3.0.11
- Platform:
- Browser:
- OS:

**Comment by Monokai** [comment]
Same here. Seems to break in the function `formatDom` when getting `nodes.length`.

**Comment by samparmenter** [comment]
Same here.

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/857#issuecomment-1456602574
