### ISSUE TITLE
Parsing wordpress category content

### ISSUE THREAD

**Issue by ElSeniorMikael** [remarkablemark/html-react-parser#864]
## Expected Behavior

Parsing the `\r\n`

## Actual Behavior

it remove `\r` and keep `\n`

## Steps to Reproduce

```js
const text = "toto \r\n toto"

parse(text)

output "toto toto"
```

## description

Wordpress now output some `\r\n` inside their description field of their category and im using wordpress as an headless cms and i fetch the data on my nextjs project but when i parse the data, im losing the flow of my content and whenever i try to use the "replace" option with the parse, it already have cleaned the "\r" from the text and i only can see those "\n" is there anyway i could include those during the parsin or i would have to replace \n by something like => `<br/>`

**Comment by ElSeniorMikael** [comment]
https://codesandbox.io/p/sandbox/wispy-haze-cd7wwp?file=%2Fpages%2Findex.js

**Comment by remarkablemark** [comment]
I can confirm that I can reproduce the issue in https://codesandbox.io/p/sandbox/html-react-parser-864-0v3xvs

This bug is coming from [html-dom-parser](https://github.com/remarkablemark/html-dom-parser)

**Comment by remarkablemark** [comment]
@ElSeniorMikael can you do this as a workaround?

```js
const text = "toto \r\n toto"

parse(text.replace(/\r/g, "\n"))
```

Or:

```js
const text = "toto \r\n toto"

parse(text.replace(/\r|\n/g, "<br>"))
```

See [CodeSandbox](https://codesandbox.io/s/html-react-parser-864-lfcybe?file=/src/index.tsx)

It seems that `innerHTML` strips out carriage returns on the client parser
