### ISSUE TITLE
Include , to index.d.ts

### ISSUE THREAD

**Issue by Jasonnnz** [remarkablemark/html-react-parser#871]
## Problem

Currently the `index.d.ts` file does not have a `,` at the end of line 10.

## Suggested Solution

Add `,` to the end of line 10

## Keywords

TS, TypeScript

**Comment by remarkablemark** [comment]
Question: what does adding the `,` do for this library?

**Comment by Jasonnnz** [comment]
Thanks for the quick reply!

I guess it'd just help avoid a TS Error - `',' expected.ts(1005)`. My builds failing due to this minor thing.

**Comment by remarkablemark** [comment]
Hmm interesting. I find it strange that TypeScript would fail on that line: https://github.com/remarkablemark/html-react-parser/blob/v3.0.12/index.d.ts#L10

I haven't experienced an issue before. What TypeScript version are you using? Possible to create a reproducible example?

**Comment by Jasonnnz** [comment]
Apologies for the confusion, after further inspection, I realized it's caused by eslint. This isn't an issue caused by TypeScript

**Comment by stilldesign** [comment]
I too am encounting this issue - 
I tried upgrading to typescript 5.0.2, and even my @typescript-eslint to the latest but still no luck

![image](https://user-images.githubusercontent.com/4223821/227406000-ae68a4cd-28ad-47d0-bef4-f2cacb811b7e.png)

**Comment by remarkablemark** [comment]
Release:

- https://github.com/remarkablemark/html-react-parser/pull/880#issuecomment-1482227813

**Comment by stilldesign** [comment]
I updated to the new package and it has solved the issue, thank you so much for the quick fix and the cool project 🙂

**Comment by remarkablemark** [comment]
@stilldesign Thanks for confirming!
