### ISSUE TITLE
How i can ignore <script>?

### ISSUE THREAD

**Issue by jslby** [remarkablemark/html-react-parser#89]
Hello. I need ignore script tag in html. How i can do it?

**Comment by remarkablemark** [comment]
See the [replace](https://github.com/remarkablemark/html-react-parser#replacedomnode) option.

There's an example on how to exclude an element.

**Comment by remarkablemark** [comment]
Was your question answered @jslby? If so, can this issue be closed?

**Comment by jslby** [comment]
Yep. Thx
