### ISSUE TITLE
React state variables in parse(...)

### ISSUE THREAD

**Issue by ghost** [remarkablemark/html-react-parser#906]
## Question

Hi all,

Please accept my apologies if I really shouldn't be asking this question, but here we go anyway. Is it possible to use React state variables with html-react-parser? Like so:

```jsx
import React from "react";
import parse from 'html-react-parser';

class TestView extends React.Component
{
  state = { testValue : "My Test Value" }

  constructor( props  )
  { super(props); }

  render()
  {
    // This works of course: 
    // return <div><p>{this.state.testValue}</p></div>;
    
    //  This does not:
    return parse( "<div><p>{this.state.testValue}</p><div>");
  }
}

```

## Keywords

react
state variables

**Comment by remarkablemark** [comment]
@simoncrowle It will work in your example if you use [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals):

```js
return parse(`<div><p>${this.state.testValue}</p><div>`);
```

But just a note, this works for values like string and number, but it won't work for types like objects or arrays.

**Comment by simoncrowle** [comment]
Thanks for this pointer, much appreciated.

**Comment by remarkablemark** [comment]
No problem! Let me know if there are any other questions

**Comment by usernein** [comment]
Hello, is there any other way of doing that than using template literals?

I want to call some methods on a variable used inside the html i want to parse, but i get that html string dinamically, so i can't hardcode it with template literals.

**Comment by remarkablemark** [comment]
@usernein I don't see any other way than using template literals. Why not create a function that calls `parse` during runtime?

```js
function getParse(dynamicString) {
  return parse(`<div>${dynamicString}</div>`);
}
```

**Comment by usernein** [comment]
> @usernein I don't see any other way than using template literals. Why not create a function that calls `parse` during runtime?
> 
> ```js
> function getParse(dynamicString) {
>   return parse(`<div>${dynamicString}</div>`);
> }
> ```

In my case, the dynamicString is something like this : "Your name is {store.getName()}"
store is a local variable and the user who is providing the dynamicString may be able to use any method of it

Templates literals will only interpolate the value of dynamicString, but will not replace any variables being used inside of it, right?

**Comment by remarkablemark** [comment]
Hmm, would it be possible to do this?

```js
function getParse(name) {
  return parse(`<div>Your name is ${name}</div>`);
}
```

And then call the method when it's available?

```js
getParse(store.getName());
```

If that's not possible, then template literal might not work for you
