### ISSUE TITLE
What is the correct way to pass props to a react component during the replace?

### ISSUE THREAD

**Issue by geocine** [remarkablemark/html-react-parser#91]
## Input 

```html
<div class="gallery">
     <img src="1.jpg" />
     <img src="2.jpg" />
</div>
```

## Output 
```
 <Gallery images={images} />
```

## Parser 
```js
const original = `
  <div class="gallery">
     <img src="1.jpg" />
     <img src="2.jpg"/>
  </div>
`;
const elements = parse(original, {
  replace: ({ attribs, children }) => {
    if (!attribs) return;
    if (attribs.class && attribs.class.includes("gallery")) {
      let photos = []
      children.forEach((img) => {
        if(img.name == 'img') {
          photos.push({
            src: img.attribs.src,
            width: 2,
            height: 2
          })
        }
      });
      return <Gallery photos={photos} />;
    }
  }
});
```

This is working fine , the `Gallery` component is being rendered , however the `photos` prop array is **not being passed down to the component** during render. What is the correct way of passing a prop?

**Comment by remarkablemark** [comment]
@geocine The `photos` prop is correctly passed to the `<Gallery>` component. You can access it in `props.photos` (functional component) or `this.props.photos` (class component). See [fiddle](https://jsfiddle.net/remarkablemark/xjqe2bks/).

**Comment by geocine** [comment]
I am opened an issue at https://github.com/gatsbyjs/gatsby/issues/11584 just in case
