### ISSUE TITLE
react server component - rsc - serverside rendering - nextjs 13 app directory

### ISSUE THREAD

**Issue by dev-aly3n** [remarkablemark/html-react-parser#954]
## Question
Hi, I made this reproducible sandbox to check if everything works as expected in a React Server Component or not.

https://codesandbox.io/p/sandbox/html-react-parser-react-server-component-nr3rdz?file=%2Fapp%2Fpage.tsx%3A8%2C2

the code explained in comments and also there is a reference to NextJs document about `fetch`

**Comment by remarkablemark** [comment]
Thanks for creating the reproducible example @dev-aly3n. I took a look and everything seems to be working correctly (didn't see any errors in the console). What is the issue that you're facing?
