### ISSUE TITLE
capability to convert attached event listeners

### ISSUE THREAD

**Issue by JMA12** [remarkablemark/html-react-parser#97]
## Expected Behavior

Created html strings with attached event listeners. The attached listeners will be preserved after conversion
## Actual Behavior

attached listeners are not processed properly

## Steps to Reproduce

    * create an element which is a string
    * For instance, "<span onClick={e => {console.log("test...")}}>TEST</span>"

![abc](https://user-images.githubusercontent.com/43695742/54990088-db37ea00-4ff4-11e9-9509-12f2c77fffb7.png)

  

## Environment

- Version:
- Platform:
- Browser:

**Comment by remarkablemark** [comment]
This is expected behavior.

`html-react-parser` will parse the event listeners from the HTML markup as a **string**. Thus, in order to call the event listener, you will need to `eval` it. If you do that, just be wary of [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting).

See #73.

**Comment by JMA12** [comment]
Yes, I see. 
As I read through #73, I found that using the replace method is much better.
Thanks @remarkablemark .
