### ISSUE TITLE
Execute Script tag in Parser

### ISSUE THREAD

**Issue by frontendpm** [remarkablemark/html-react-parser#98]
Hi,
is it possible to parse script tag? In my case I get the html code with script tag as a string from some endpoint, and I wish to put it into my react component and make it works.

So for example on the end I am trying to do something similar to this:
`Parser('<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>') `
Unfortunately this library is not loaded to the browser. Did I do something wrong?

**Comment by remarkablemark** [comment]
Although `<script>` markup is parsed by `html-react-parser`, it actually isn't rendered by `react-dom`.

I recently discovered this while troubleshooting #94.

To load a script, you will need to programmatically create and append a script element using [`replace`](https://github.com/remarkablemark/html-react-parser#replacedomnode). See [fiddle](https://jsfiddle.net/remarkablemark/3h8ejw9n/).

**Comment by remarkablemark** [comment]
Was your question answered @frontendpm? Let me know what else you need in order to close the issue.

**Comment by frontendpm** [comment]
Thank mate, it works perfectly!

**Comment by rinkusam12** [comment]
How should I do this in NextJS

**Comment by mcviswanadha** [comment]
Hi, will this one work in react helmet for below

<script type="text/javascript" src='https://www.cdn.com/shared/pp/sdvice/dyncdn/<esi:include src="https://www.cdn.com/shared/pp/sdvice/sttcdn/version" onerror="continue"></esi:include>/vice_loader/perf.js'></script>

**Comment by lhguerra** [comment]
A little late pherhaps but in Next JS you would use the Script component: https://nextjs.org/docs/api-reference/next/script

**Comment by katefadeeva** [comment]
Can you help me? But what if there are several script tags?
